// ─────────────────────────────────────────────────────────────
// guestStrings — textele fluxului OASPETELUI (coș, fișa produsului,
// urmărirea comenzii, plata la masă, împărțirea notei, ridicare, rezervare,
// ecranul de plată, erorile de server traduse) în cele 7 limbi ale meniului.
//
// Intră în PUBLIC_MENU_STRINGS prin spread (publicMenuStrings.ts), deci se
// citesc cu același `T(lang, key)`. Fișier separat ca tabela de bază să nu
// devină un punct de conflict permanent. Modul FĂRĂ importuri: ajunge doar în
// chunk-urile de meniu (aceeași disciplină ca publicMenuStrings, OPT-11).
//
// Reguli (clichet în src/lib/__tests__/guestI18n.test.ts):
//   • fiecare cheie are TOATE cele 7 limbi, ne-goale;
//   • substituțiile `{nume}` sunt IDENTICE în toate limbile (Tf le înlocuiește);
//   • pe Planul 2 Menuvia nu încasează nimic — niciun text de aici nu promite
//     „plătit" în afara ramurilor care chiar sunt plăți (online / `paid`).
// ─────────────────────────────────────────────────────────────

export const GUEST_STRINGS = {
  // ── Urmărirea comenzii (OrderTracker + ActiveOrdersBanner) ──
  ot_step_new: {
    ro: 'Trimisă',
    en: 'Sent',
    de: 'Gesendet',
    fr: 'Envoyée',
    it: 'Inviato',
    hu: 'Elküldve',
    es: 'Enviado',
  },
  ot_step_confirmed: {
    ro: 'Confirmată',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  ot_step_preparing: {
    ro: 'În preparare',
    en: 'Being prepared',
    de: 'In Zubereitung',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'En preparación',
  },
  ot_step_ready: {
    ro: 'Gata de servit',
    en: 'Ready to serve',
    de: 'Servierbereit',
    fr: 'Prête à servir',
    it: 'Pronto da servire',
    hu: 'Tálalásra kész',
    es: 'Listo para servir',
  },
  ot_step_served: {
    ro: 'Servită',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  ot_sent_title: {
    ro: 'Comanda a fost trimisă',
    en: 'Your order has been sent',
    de: 'Deine Bestellung wurde gesendet',
    fr: 'Votre commande a été envoyée',
    it: 'Il tuo ordine è stato inviato',
    hu: 'A rendelésedet elküldtük',
    es: 'Tu pedido ha sido enviado',
  },
  ot_kitchen_received: {
    ro: 'Bucătăria a primit comanda.',
    en: 'The kitchen has received your order.',
    de: 'Die Küche hat deine Bestellung erhalten.',
    fr: 'La cuisine a reçu votre commande.',
    it: 'La cucina ha ricevuto il tuo ordine.',
    hu: 'A konyha megkapta a rendelésedet.',
    es: 'La cocina ha recibido tu pedido.',
  },
  ot_limited: {
    ro: 'Urmărirea comenzii nu mai este disponibilă complet.',
    en: 'Full order tracking is no longer available.',
    de: 'Die vollständige Bestellverfolgung ist nicht mehr verfügbar.',
    fr: 'Le suivi complet de la commande n’est plus disponible.',
    it: 'Il monitoraggio completo dell’ordine non è più disponibile.',
    hu: 'A rendelés teljes követése már nem érhető el.',
    es: 'El seguimiento completo del pedido ya no está disponible.',
  },
  ask_staff: {
    ro: 'Te rugăm să întrebi personalul.',
    en: 'Please ask the staff.',
    de: 'Bitte frag das Personal.',
    fr: 'Merci de demander au personnel.',
    it: 'Chiedi al personale, per favore.',
    hu: 'Kérjük, kérdezd meg a személyzetet.',
    es: 'Pregunta al personal, por favor.',
  },
  ot_cancelled: {
    ro: 'Comanda a fost anulată',
    en: 'Your order was cancelled',
    de: 'Deine Bestellung wurde storniert',
    fr: 'Votre commande a été annulée',
    it: 'Il tuo ordine è stato annullato',
    hu: 'A rendelésedet törölték',
    es: 'Tu pedido ha sido cancelado',
  },
  ot_now: {
    ro: 'Acum',
    en: 'Now',
    de: 'Jetzt',
    fr: 'Maintenant',
    it: 'Ora',
    hu: 'Most',
    es: 'Ahora',
  },
  add_more_items: {
    ro: '+ Adaugă produse',
    en: '+ Add more items',
    de: '+ Weitere Artikel hinzufügen',
    fr: '+ Ajouter des articles',
    it: '+ Aggiungi prodotti',
    hu: '+ További tételek',
    es: '+ Añadir productos',
  },
  ot_new_order: {
    ro: 'Comandă nouă',
    en: 'New order',
    de: 'Neue Bestellung',
    fr: 'Nouvelle commande',
    it: 'Nuovo ordine',
    hu: 'Új rendelés',
    es: 'Nuevo pedido',
  },
  ot_close_session: {
    ro: 'Închide sesiunea',
    en: 'Close session',
    de: 'Sitzung beenden',
    fr: 'Fermer la session',
    it: 'Chiudi la sessione',
    hu: 'Munkamenet bezárása',
    es: 'Cerrar la sesión',
  },
  ot_session_total: {
    ro: 'Total sesiune:',
    en: 'Session total:',
    de: 'Summe der Sitzung:',
    fr: 'Total de la session :',
    it: 'Totale della sessione:',
    hu: 'Munkamenet összesen:',
    es: 'Total de la sesión:',
  },
  order_one: {
    ro: 'comandă',
    en: 'order',
    de: 'Bestellung',
    fr: 'commande',
    it: 'ordine',
    hu: 'rendelés',
    es: 'pedido',
  },
  order_many: {
    ro: 'comenzi',
    en: 'orders',
    de: 'Bestellungen',
    fr: 'commandes',
    it: 'ordini',
    hu: 'rendelés',
    es: 'pedidos',
  },
  total_suffix: {
    ro: 'total',
    en: 'total',
    de: 'gesamt',
    fr: 'au total',
    it: 'in totale',
    hu: 'összesen',
    es: 'en total',
  },
  active_one: {
    ro: 'activă',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivo',
    hu: 'aktív',
    es: 'activo',
  },
  active_many: {
    ro: 'active',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivi',
    hu: 'aktív',
    es: 'activos',
  },
  order_hash: {
    ro: 'Comanda #',
    en: 'Order #',
    de: 'Bestellung #',
    fr: 'Commande n° ',
    it: 'Ordine #',
    hu: 'Rendelés #',
    es: 'Pedido #',
  },
  st_new: {
    ro: 'Primit',
    en: 'Received',
    de: 'Eingegangen',
    fr: 'Reçue',
    it: 'Ricevuto',
    hu: 'Beérkezett',
    es: 'Recibido',
  },
  st_confirmed: {
    ro: 'Confirmat',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  st_preparing: {
    ro: 'Se prepară',
    en: 'Preparing',
    de: 'Wird zubereitet',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'Preparándose',
  },
  st_served: {
    ro: 'Servit',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  st_paid: {
    ro: 'Plătit',
    en: 'Paid',
    de: 'Bezahlt',
    fr: 'Payée',
    it: 'Pagato',
    hu: 'Fizetve',
    es: 'Pagado',
  },
  st_closed: {
    ro: 'Închisă',
    en: 'Closed',
    de: 'Abgeschlossen',
    fr: 'Clôturée',
    it: 'Chiuso',
    hu: 'Lezárva',
    es: 'Cerrado',
  },
  st_cancelled: {
    ro: 'Anulat',
    en: 'Cancelled',
    de: 'Storniert',
    fr: 'Annulée',
    it: 'Annullato',
    hu: 'Törölve',
    es: 'Cancelado',
  },

  // ── Ecranul „Plată confirmată" + feedback (PaymentConfirmedScreen) ──
  paid_title: {
    ro: 'Plată confirmată!',
    en: 'Payment confirmed!',
    de: 'Zahlung bestätigt!',
    fr: 'Paiement confirmé !',
    it: 'Pagamento confermato!',
    hu: 'Fizetés visszaigazolva!',
    es: '¡Pago confirmado!',
  },
  paid_subtitle: {
    ro: 'Personalul restaurantului știe deja că masa a fost plătită.\nÎți mulțumim pentru vizită!',
    en: 'The restaurant staff already knows your table has been paid.\nThank you for your visit!',
    de: 'Das Restaurantpersonal weiß bereits, dass dein Tisch bezahlt ist.\nDanke für deinen Besuch!',
    fr: 'Le personnel du restaurant sait déjà que votre table a été réglée.\nMerci de votre visite !',
    it: 'Il personale del ristorante sa già che il tavolo è stato pagato.\nGrazie per la visita!',
    hu: 'Az étterem személyzete már tudja, hogy az asztalt kifizették.\nKöszönjük a látogatást!',
    es: 'El personal del restaurante ya sabe que la mesa está pagada.\n¡Gracias por tu visita!',
  },
  subtotal: {
    ro: 'Subtotal',
    en: 'Subtotal',
    de: 'Zwischensumme',
    fr: 'Sous-total',
    it: 'Subtotale',
    hu: 'Részösszeg',
    es: 'Subtotal',
  },
  tip: {
    ro: 'Bacșiș',
    en: 'Tip',
    de: 'Trinkgeld',
    fr: 'Pourboire',
    it: 'Mancia',
    hu: 'Borravaló',
    es: 'Propina',
  },
  fast_pay_fee: {
    ro: 'Comision plată rapidă',
    en: 'Fast pay fee',
    de: 'Gebühr für Schnellzahlung',
    fr: 'Frais de paiement rapide',
    it: 'Commissione pagamento rapido',
    hu: 'Gyorsfizetési díj',
    es: 'Comisión de pago rápido',
  },
  need_fiscal_receipt: {
    ro: 'Am nevoie de bonul fiscal',
    en: 'I need the fiscal receipt',
    de: 'Ich brauche den Kassenbon',
    fr: 'J’ai besoin du ticket de caisse',
    it: 'Mi serve lo scontrino fiscale',
    hu: 'Kérem a nyugtát',
    es: 'Necesito el ticket fiscal',
  },
  fiscal_requested: {
    ro: 'Bonul fiscal a fost cerut',
    en: 'Fiscal receipt requested',
    de: 'Kassenbon angefordert',
    fr: 'Ticket de caisse demandé',
    it: 'Scontrino fiscale richiesto',
    hu: 'Nyugta kérve',
    es: 'Ticket fiscal solicitado',
  },
  powered_by: {
    ro: 'Realizat cu',
    en: 'Powered by',
    de: 'Bereitgestellt von',
    fr: 'Propulsé par',
    it: 'Realizzato con',
    hu: 'Készítette:',
    es: 'Con la tecnología de',
  },
  fb_title: {
    ro: 'Opinia ta contează',
    en: 'Your opinion matters',
    de: 'Deine Meinung zählt',
    fr: 'Votre avis compte',
    it: 'La tua opinione conta',
    hu: 'Számít a véleményed',
    es: 'Tu opinión importa',
  },
  fb_thanks: {
    ro: 'Îți mulțumim pentru feedback',
    en: 'Thank you for your feedback',
    de: 'Danke für dein Feedback',
    fr: 'Merci pour votre avis',
    it: 'Grazie per il tuo feedback',
    hu: 'Köszönjük a visszajelzést',
    es: 'Gracias por tu opinión',
  },
  fb_ask_payment: {
    ro: 'Cum a fost experiența de plată?',
    en: 'How was the payment experience?',
    de: 'Wie war das Bezahlen?',
    fr: 'Comment s’est passé le paiement ?',
    it: 'Com’è andato il pagamento?',
    hu: 'Milyen volt a fizetés?',
    es: '¿Qué tal fue el pago?',
  },
  fb_ask_service: {
    ro: 'Cum a fost servirea?',
    en: 'How was the service?',
    de: 'Wie war der Service?',
    fr: 'Comment était le service ?',
    it: 'Com’è stato il servizio?',
    hu: 'Milyen volt a kiszolgálás?',
    es: '¿Qué tal fue el servicio?',
  },
  fb_ask_food: {
    ro: 'Cum a fost mâncarea?',
    en: 'How was the food?',
    de: 'Wie war das Essen?',
    fr: 'Comment était le repas ?',
    it: 'Com’era il cibo?',
    hu: 'Milyen volt az étel?',
    es: '¿Qué tal estuvo la comida?',
  },
  fb_negative: {
    ro: 'Ne pare rău. Ce putem îmbunătăți?',
    en: 'We are sorry. What can we improve?',
    de: 'Das tut uns leid. Was können wir besser machen?',
    fr: 'Nous sommes désolés. Que pouvons-nous améliorer ?',
    it: 'Ci dispiace. Cosa possiamo migliorare?',
    hu: 'Sajnáljuk. Min javíthatnánk?',
    es: 'Lo sentimos. ¿Qué podemos mejorar?',
  },
  fb_negative_placeholder: {
    ro: 'Scrie-ne aici...',
    en: 'Write to us here...',
    de: 'Schreib uns hier...',
    fr: 'Écrivez-nous ici...',
    it: 'Scrivici qui...',
    hu: 'Írj nekünk ide...',
    es: 'Escríbenos aquí...',
  },
  fb_google_text: {
    ro: 'Spune-le și altora despre experiența ta la',
    en: 'Tell others about your experience at',
    de: 'Erzähl anderen von deinem Besuch bei',
    fr: 'Partagez votre expérience chez',
    it: 'Racconta agli altri la tua esperienza da',
    hu: 'Meséld el másoknak is az élményed itt:',
    es: 'Cuéntales a otros tu experiencia en',
  },
  fb_google_button: {
    ro: 'Scrie o recenzie pe Google',
    en: 'Write a Google review',
    de: 'Google-Bewertung schreiben',
    fr: 'Laisser un avis Google',
    it: 'Scrivi una recensione su Google',
    hu: 'Írj értékelést a Google-on',
    es: 'Escribe una reseña en Google',
  },
  fb_thumb_up: {
    ro: 'Bine',
    en: 'Good',
    de: 'Gut',
    fr: 'Bien',
    it: 'Bene',
    hu: 'Jó',
    es: 'Bien',
  },
  fb_thumb_down: {
    ro: 'Nu prea bine',
    en: 'Not so good',
    de: 'Nicht so gut',
    fr: 'Pas terrible',
    it: 'Non molto bene',
    hu: 'Nem túl jó',
    es: 'No muy bien',
  },
  fb_stars: {
    ro: '{n} stele',
    en: '{n} stars',
    de: '{n} Sterne',
    fr: '{n} étoiles',
    it: '{n} stelle',
    hu: '{n} csillag',
    es: '{n} estrellas',
  },
} as const
