// ─────────────────────────────────────────────────────────────
// guestStrings — textele fluxului OASPETELUI (coș, fișa produsului,
// urmărirea comenzii, plata la masă, împărțirea notei, ridicare, rezervare,
// ecranul de plată, erorile de server traduse) în cele 7 limbi ale meniului.
//
// Intră în PUBLIC_MENU_STRINGS prin spread (publicMenuStrings.ts), deci se
// citesc cu același `T(lang, key)`. Fișier separat ca tabela de bază să nu
// devină un punct de conflict permanent. Modul FĂRĂ importuri: ajunge doar în
// chunk-urile de meniu (aceeași disciplină ca publicMenuStrings, OPT-11).
//
// Reguli (clichet în src/lib/__tests__/guestI18n.test.ts):
//   • fiecare cheie are TOATE cele 7 limbi, ne-goale;
//   • substituțiile `{nume}` sunt IDENTICE în toate limbile (Tf le înlocuiește);
//   • pe Planul 2 Menuvia nu încasează nimic — niciun text de aici nu promite
//     „plătit" în afara ramurilor care chiar sunt plăți (online / `paid`).
// ─────────────────────────────────────────────────────────────

export const GUEST_STRINGS = {
  // ── Urmărirea comenzii (OrderTracker + ActiveOrdersBanner) ──
  ot_step_new: {
    ro: 'Trimisă',
    en: 'Sent',
    de: 'Gesendet',
    fr: 'Envoyée',
    it: 'Inviato',
    hu: 'Elküldve',
    es: 'Enviado',
  },
  ot_step_confirmed: {
    ro: 'Confirmată',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  ot_step_preparing: {
    ro: 'În preparare',
    en: 'Being prepared',
    de: 'In Zubereitung',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'En preparación',
  },
  ot_step_ready: {
    ro: 'Gata de servit',
    en: 'Ready to serve',
    de: 'Servierbereit',
    fr: 'Prête à servir',
    it: 'Pronto da servire',
    hu: 'Tálalásra kész',
    es: 'Listo para servir',
  },
  ot_step_served: {
    ro: 'Servită',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  ot_sent_title: {
    ro: 'Comanda a fost trimisă',
    en: 'Your order has been sent',
    de: 'Deine Bestellung wurde gesendet',
    fr: 'Votre commande a été envoyée',
    it: 'Il tuo ordine è stato inviato',
    hu: 'A rendelésedet elküldtük',
    es: 'Tu pedido ha sido enviado',
  },
  ot_kitchen_received: {
    ro: 'Bucătăria a primit comanda.',
    en: 'The kitchen has received your order.',
    de: 'Die Küche hat deine Bestellung erhalten.',
    fr: 'La cuisine a reçu votre commande.',
    it: 'La cucina ha ricevuto il tuo ordine.',
    hu: 'A konyha megkapta a rendelésedet.',
    es: 'La cocina ha recibido tu pedido.',
  },
  ot_limited: {
    ro: 'Urmărirea comenzii nu mai este disponibilă complet.',
    en: 'Full order tracking is no longer available.',
    de: 'Die vollständige Bestellverfolgung ist nicht mehr verfügbar.',
    fr: 'Le suivi complet de la commande n’est plus disponible.',
    it: 'Il monitoraggio completo dell’ordine non è più disponibile.',
    hu: 'A rendelés teljes követése már nem érhető el.',
    es: 'El seguimiento completo del pedido ya no está disponible.',
  },
  ask_staff: {
    ro: 'Te rugăm să întrebi personalul.',
    en: 'Please ask the staff.',
    de: 'Bitte frag das Personal.',
    fr: 'Merci de demander au personnel.',
    it: 'Chiedi al personale, per favore.',
    hu: 'Kérjük, kérdezd meg a személyzetet.',
    es: 'Pregunta al personal, por favor.',
  },
  ot_cancelled: {
    ro: 'Comanda a fost anulată',
    en: 'Your order was cancelled',
    de: 'Deine Bestellung wurde storniert',
    fr: 'Votre commande a été annulée',
    it: 'Il tuo ordine è stato annullato',
    hu: 'A rendelésedet törölték',
    es: 'Tu pedido ha sido cancelado',
  },
  ot_now: {
    ro: 'Acum',
    en: 'Now',
    de: 'Jetzt',
    fr: 'Maintenant',
    it: 'Ora',
    hu: 'Most',
    es: 'Ahora',
  },
  add_more_items: {
    ro: '+ Adaugă produse',
    en: '+ Add more items',
    de: '+ Weitere Artikel hinzufügen',
    fr: '+ Ajouter des articles',
    it: '+ Aggiungi prodotti',
    hu: '+ További tételek',
    es: '+ Añadir productos',
  },
  ot_new_order: {
    ro: 'Comandă nouă',
    en: 'New order',
    de: 'Neue Bestellung',
    fr: 'Nouvelle commande',
    it: 'Nuovo ordine',
    hu: 'Új rendelés',
    es: 'Nuevo pedido',
  },
  ot_close_session: {
    ro: 'Închide sesiunea',
    en: 'Close session',
    de: 'Sitzung beenden',
    fr: 'Fermer la session',
    it: 'Chiudi la sessione',
    hu: 'Munkamenet bezárása',
    es: 'Cerrar la sesión',
  },
  ot_session_total: {
    ro: 'Total sesiune:',
    en: 'Session total:',
    de: 'Summe der Sitzung:',
    fr: 'Total de la session :',
    it: 'Totale della sessione:',
    hu: 'Munkamenet összesen:',
    es: 'Total de la sesión:',
  },
  order_one: {
    ro: 'comandă',
    en: 'order',
    de: 'Bestellung',
    fr: 'commande',
    it: 'ordine',
    hu: 'rendelés',
    es: 'pedido',
  },
  order_many: {
    ro: 'comenzi',
    en: 'orders',
    de: 'Bestellungen',
    fr: 'commandes',
    it: 'ordini',
    hu: 'rendelés',
    es: 'pedidos',
  },
  total_suffix: {
    ro: 'total',
    en: 'total',
    de: 'gesamt',
    fr: 'au total',
    it: 'in totale',
    hu: 'összesen',
    es: 'en total',
  },
  active_one: {
    ro: 'activă',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivo',
    hu: 'aktív',
    es: 'activo',
  },
  active_many: {
    ro: 'active',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivi',
    hu: 'aktív',
    es: 'activos',
  },
  order_hash: {
    ro: 'Comanda #',
    en: 'Order #',
    de: 'Bestellung #',
    fr: 'Commande n° ',
    it: 'Ordine #',
    hu: 'Rendelés #',
    es: 'Pedido #',
  },
  st_new: {
    ro: 'Primit',
    en: 'Received',
    de: 'Eingegangen',
    fr: 'Reçue',
    it: 'Ricevuto',
    hu: 'Beérkezett',
    es: 'Recibido',
  },
  st_confirmed: {
    ro: 'Confirmat',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  st_preparing: {
    ro: 'Se prepară',
    en: 'Preparing',
    de: 'Wird zubereitet',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'Preparándose',
  },
  st_served: {
    ro: 'Servit',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  st_paid: {
    ro: 'Plătit',
    en: 'Paid',
    de: 'Bezahlt',
    fr: 'Payée',
    it: 'Pagato',
    hu: 'Fizetve',
    es: 'Pagado',
  },
  st_closed: {
    ro: 'Închisă',
    en: 'Closed',
    de: 'Abgeschlossen',
    fr: 'Clôturée',
    it: 'Chiuso',
    hu: 'Lezárva',
    es: 'Cerrado',
  },
  st_cancelled: {
    ro: 'Anulat',
    en: 'Cancelled',
    de: 'Storniert',
    fr: 'Annulée',
    it: 'Annullato',
    hu: 'Törölve',
    es: 'Cancelado',
  },

  // ── Ecranul „Plată confirmată" + feedback (PaymentConfirmedScreen) ──
  paid_title: {
    ro: 'Plată confirmată!',
    en: 'Payment confirmed!',
    de: 'Zahlung bestätigt!',
    fr: 'Paiement confirmé !',
    it: 'Pagamento confermato!',
    hu: 'Fizetés visszaigazolva!',
    es: '¡Pago confirmado!',
  },
  paid_subtitle: {
    ro: 'Personalul restaurantului știe deja că masa a fost plătită.\nÎți mulțumim pentru vizită!',
    en: 'The restaurant staff already knows your table has been paid.\nThank you for your visit!',
    de: 'Das Restaurantpersonal weiß bereits, dass dein Tisch bezahlt ist.\nDanke für deinen Besuch!',
    fr: 'Le personnel du restaurant sait déjà que votre table a été réglée.\nMerci de votre visite !',
    it: 'Il personale del ristorante sa già che il tavolo è stato pagato.\nGrazie per la visita!',
    hu: 'Az étterem személyzete már tudja, hogy az asztalt kifizették.\nKöszönjük a látogatást!',
    es: 'El personal del restaurante ya sabe que la mesa está pagada.\n¡Gracias por tu visita!',
  },
  subtotal: {
    ro: 'Subtotal',
    en: 'Subtotal',
    de: 'Zwischensumme',
    fr: 'Sous-total',
    it: 'Subtotale',
    hu: 'Részösszeg',
    es: 'Subtotal',
  },
  tip: {
    ro: 'Bacșiș',
    en: 'Tip',
    de: 'Trinkgeld',
    fr: 'Pourboire',
    it: 'Mancia',
    hu: 'Borravaló',
    es: 'Propina',
  },
  fast_pay_fee: {
    ro: 'Comision plată rapidă',
    en: 'Fast pay fee',
    de: 'Gebühr für Schnellzahlung',
    fr: 'Frais de paiement rapide',
    it: 'Commissione pagamento rapido',
    hu: 'Gyorsfizetési díj',
    es: 'Comisión de pago rápido',
  },
  need_fiscal_receipt: {
    ro: 'Am nevoie de bonul fiscal',
    en: 'I need the fiscal receipt',
    de: 'Ich brauche den Kassenbon',
    fr: 'J’ai besoin du ticket de caisse',
    it: 'Mi serve lo scontrino fiscale',
    hu: 'Kérem a nyugtát',
    es: 'Necesito el ticket fiscal',
  },
  fiscal_requested: {
    ro: 'Bonul fiscal a fost cerut',
    en: 'Fiscal receipt requested',
    de: 'Kassenbon angefordert',
    fr: 'Ticket de caisse demandé',
    it: 'Scontrino fiscale richiesto',
    hu: 'Nyugta kérve',
    es: 'Ticket fiscal solicitado',
  },
  powered_by: {
    ro: 'Realizat cu',
    en: 'Powered by',
    de: 'Bereitgestellt von',
    fr: 'Propulsé par',
    it: 'Realizzato con',
    hu: 'Készítette:',
    es: 'Con la tecnología de',
  },
  fb_title: {
    ro: 'Opinia ta contează',
    en: 'Your opinion matters',
    de: 'Deine Meinung zählt',
    fr: 'Votre avis compte',
    it: 'La tua opinione conta',
    hu: 'Számít a véleményed',
    es: 'Tu opinión importa',
  },
  fb_thanks: {
    ro: 'Îți mulțumim pentru feedback',
    en: 'Thank you for your feedback',
    de: 'Danke für dein Feedback',
    fr: 'Merci pour votre avis',
    it: 'Grazie per il tuo feedback',
    hu: 'Köszönjük a visszajelzést',
    es: 'Gracias por tu opinión',
  },
  fb_ask_payment: {
    ro: 'Cum a fost experiența de plată?',
    en: 'How was the payment experience?',
    de: 'Wie war das Bezahlen?',
    fr: 'Comment s’est passé le paiement ?',
    it: 'Com’è andato il pagamento?',
    hu: 'Milyen volt a fizetés?',
    es: '¿Qué tal fue el pago?',
  },
  fb_ask_service: {
    ro: 'Cum a fost servirea?',
    en: 'How was the service?',
    de: 'Wie war der Service?',
    fr: 'Comment était le service ?',
    it: 'Com’è stato il servizio?',
    hu: 'Milyen volt a kiszolgálás?',
    es: '¿Qué tal fue el servicio?',
  },
  fb_ask_food: {
    ro: 'Cum a fost mâncarea?',
    en: 'How was the food?',
    de: 'Wie war das Essen?',
    fr: 'Comment était le repas ?',
    it: 'Com’era il cibo?',
    hu: 'Milyen volt az étel?',
    es: '¿Qué tal estuvo la comida?',
  },
  fb_negative: {
    ro: 'Ne pare rău. Ce putem îmbunătăți?',
    en: 'We are sorry. What can we improve?',
    de: 'Das tut uns leid. Was können wir besser machen?',
    fr: 'Nous sommes désolés. Que pouvons-nous améliorer ?',
    it: 'Ci dispiace. Cosa possiamo migliorare?',
    hu: 'Sajnáljuk. Min javíthatnánk?',
    es: 'Lo sentimos. ¿Qué podemos mejorar?',
  },
  fb_negative_placeholder: {
    ro: 'Scrie-ne aici...',
    en: 'Write to us here...',
    de: 'Schreib uns hier...',
    fr: 'Écrivez-nous ici...',
    it: 'Scrivici qui...',
    hu: 'Írj nekünk ide...',
    es: 'Escríbenos aquí...',
  },
  fb_google_text: {
    ro: 'Spune-le și altora despre experiența ta la',
    en: 'Tell others about your experience at',
    de: 'Erzähl anderen von deinem Besuch bei',
    fr: 'Partagez votre expérience chez',
    it: 'Racconta agli altri la tua esperienza da',
    hu: 'Meséld el másoknak is az élményed itt:',
    es: 'Cuéntales a otros tu experiencia en',
  },
  fb_google_button: {
    ro: 'Scrie o recenzie pe Google',
    en: 'Write a Google review',
    de: 'Google-Bewertung schreiben',
    fr: 'Laisser un avis Google',
    it: 'Scrivi una recensione su Google',
    hu: 'Írj értékelést a Google-on',
    es: 'Escribe una reseña en Google',
  },
  fb_thumb_up: {
    ro: 'Bine',
    en: 'Good',
    de: 'Gut',
    fr: 'Bien',
    it: 'Bene',
    hu: 'Jó',
    es: 'Bien',
  },
  fb_thumb_down: {
    ro: 'Nu prea bine',
    en: 'Not so good',
    de: 'Nicht so gut',
    fr: 'Pas terrible',
    it: 'Non molto bene',
    hu: 'Nem túl jó',
    es: 'No muy bien',
  },
  fb_stars: {
    ro: '{n} stele',
    en: '{n} stars',
    de: '{n} Sterne',
    fr: '{n} étoiles',
    it: '{n} stelle',
    hu: '{n} csillag',
    es: '{n} estrellas',
  },
  // ── Erori de server traduse (describeGuestError, lib/guestErrors.ts) ──
  err_generic: {
    ro: 'A apărut o eroare. Încearcă din nou.',
    en: 'Something went wrong. Please try again.',
    de: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
    fr: 'Une erreur s’est produite. Veuillez réessayer.',
    it: 'Si è verificato un errore. Riprova.',
    hu: 'Hiba történt. Kérjük, próbáld újra.',
    es: 'Algo salió mal. Inténtalo de nuevo.',
  },
  err_network: {
    ro: 'Conexiune slabă. Verifică internetul și încearcă din nou.',
    en: 'Weak connection. Check your internet and try again.',
    de: 'Schwache Verbindung. Prüfe deine Internetverbindung und versuche es erneut.',
    fr: 'Connexion faible. Vérifiez votre connexion internet et réessayez.',
    it: 'Connessione debole. Controlla internet e riprova.',
    hu: 'Gyenge kapcsolat. Ellenőrizd az internetet, és próbáld újra.',
    es: 'Conexión débil. Revisa tu conexión a internet e inténtalo de nuevo.',
  },
  err_order_not_sent: {
    ro: 'Comanda nu s-a trimis. Încearcă din nou.',
    en: 'Your order was not sent. Please try again.',
    de: 'Deine Bestellung wurde nicht gesendet. Bitte versuche es erneut.',
    fr: 'Votre commande n’a pas été envoyée. Veuillez réessayer.',
    it: 'L’ordine non è stato inviato. Riprova.',
    hu: 'A rendelés nem ment el. Kérjük, próbáld újra.',
    es: 'Tu pedido no se ha enviado. Inténtalo de nuevo.',
  },
  err_order_not_sent_network: {
    ro: 'Comanda nu s-a trimis — conexiune slabă. Verifică internetul și încearcă din nou.',
    en: 'Your order was not sent — weak connection. Check your internet and try again.',
    de: 'Deine Bestellung wurde nicht gesendet – schwache Verbindung. Prüfe dein Internet und versuche es erneut.',
    fr: 'Votre commande n’a pas été envoyée — connexion faible. Vérifiez votre connexion et réessayez.',
    it: 'L’ordine non è stato inviato: connessione debole. Controlla internet e riprova.',
    hu: 'A rendelés nem ment el – gyenge kapcsolat. Ellenőrizd az internetet, és próbáld újra.',
    es: 'Tu pedido no se ha enviado: conexión débil. Revisa internet e inténtalo de nuevo.',
  },
  err_missing_required_group: {
    ro: 'Un produs din coș are opțiuni obligatorii neselectate. Deschide-l și alege opțiunile.',
    en: 'An item in your cart has required options not selected. Open it and choose them.',
    de: 'Bei einem Artikel im Warenkorb fehlen Pflichtoptionen. Öffne ihn und wähle sie aus.',
    fr: 'Un article du panier a des options obligatoires non choisies. Ouvrez-le pour les choisir.',
    it: 'Un prodotto nel carrello ha opzioni obbligatorie non scelte. Aprilo e sceglile.',
    hu: 'A kosár egyik tételénél nincs kiválasztva kötelező opció. Nyisd meg, és válassz.',
    es: 'Un producto del carrito tiene opciones obligatorias sin elegir. Ábrelo y elígelas.',
  },
  err_product_unavailable: {
    ro: 'Un produs din coș nu mai este disponibil. Scoate-l și încearcă din nou.',
    en: 'An item in your cart is no longer available. Remove it and try again.',
    de: 'Ein Artikel im Warenkorb ist nicht mehr verfügbar. Entferne ihn und versuche es erneut.',
    fr: 'Un article du panier n’est plus disponible. Retirez-le et réessayez.',
    it: 'Un prodotto nel carrello non è più disponibile. Rimuovilo e riprova.',
    hu: 'A kosár egyik tétele már nem elérhető. Vedd ki, és próbáld újra.',
    es: 'Un producto del carrito ya no está disponible. Quítalo e inténtalo de nuevo.',
  },
  err_invalid_quantity: {
    ro: 'Cantitate invalidă — maximum 20 bucăți pe produs.',
    en: 'Invalid quantity — maximum 20 per item.',
    de: 'Ungültige Menge – höchstens 20 pro Artikel.',
    fr: 'Quantité invalide — 20 maximum par article.',
    it: 'Quantità non valida: massimo 20 per prodotto.',
    hu: 'Érvénytelen mennyiség – tételenként legfeljebb 20.',
    es: 'Cantidad no válida: máximo 20 por producto.',
  },
  err_too_many_items: {
    ro: 'Comanda are prea multe produse (maximum 30). Trimite restul într-o comandă separată.',
    en: 'Your order has too many items (maximum 30). Send the rest in a separate order.',
    de: 'Deine Bestellung hat zu viele Artikel (höchstens 30). Sende den Rest in einer weiteren Bestellung.',
    fr: 'Votre commande contient trop d’articles (30 maximum). Envoyez le reste dans une autre commande.',
    it: 'L’ordine ha troppi prodotti (massimo 30). Invia il resto in un ordine separato.',
    hu: 'Túl sok tétel van a rendelésben (legfeljebb 30). A többit küldd külön rendelésben.',
    es: 'Tu pedido tiene demasiados productos (máximo 30). Envía el resto en otro pedido.',
  },
  err_no_items: {
    ro: 'Coșul e gol. Adaugă produse din meniu.',
    en: 'Your cart is empty. Add items from the menu.',
    de: 'Dein Warenkorb ist leer. Füge Artikel aus dem Menü hinzu.',
    fr: 'Votre panier est vide. Ajoutez des articles depuis le menu.',
    it: 'Il carrello è vuoto. Aggiungi prodotti dal menu.',
    hu: 'A kosár üres. Adj hozzá tételeket a menüből.',
    es: 'Tu carrito está vacío. Añade productos del menú.',
  },
  err_invalid_options: {
    ro: 'Opțiunile unui produs nu mai sunt valide. Scoate produsul din coș și adaugă-l din nou.',
    en: 'The options of an item are no longer valid. Remove it from the cart and add it again.',
    de: 'Die Optionen eines Artikels sind nicht mehr gültig. Entferne ihn und füge ihn erneut hinzu.',
    fr: 'Les options d’un article ne sont plus valides. Retirez-le du panier et ajoutez-le à nouveau.',
    it: 'Le opzioni di un prodotto non sono più valide. Rimuovilo dal carrello e aggiungilo di nuovo.',
    hu: 'Egy tétel opciói már nem érvényesek. Vedd ki a kosárból, és add hozzá újra.',
    es: 'Las opciones de un producto ya no son válidas. Quítalo del carrito y vuelve a añadirlo.',
  },
  err_notes_too_long: {
    ro: 'Mențiunea e prea lungă. Scurteaz-o și încearcă din nou.',
    en: 'Your note is too long. Shorten it and try again.',
    de: 'Deine Anmerkung ist zu lang. Kürze sie und versuche es erneut.',
    fr: 'Votre remarque est trop longue. Raccourcissez-la et réessayez.',
    it: 'La nota è troppo lunga. Accorciala e riprova.',
    hu: 'A megjegyzés túl hosszú. Rövidítsd le, és próbáld újra.',
    es: 'Tu nota es demasiado larga. Acórtala e inténtalo de nuevo.',
  },
  err_session_closed: {
    ro: 'Masa a fost închisă sau sesiunea a expirat. Scanează din nou codul QR.',
    en: 'The table was closed or the session expired. Scan the QR code again.',
    de: 'Der Tisch wurde geschlossen oder die Sitzung ist abgelaufen. Scanne den QR-Code erneut.',
    fr: 'La table a été clôturée ou la session a expiré. Scannez à nouveau le QR code.',
    it: 'Il tavolo è stato chiuso o la sessione è scaduta. Scansiona di nuovo il codice QR.',
    hu: 'Az asztalt lezárták, vagy lejárt a munkamenet. Olvasd be újra a QR-kódot.',
    es: 'La mesa se ha cerrado o la sesión ha caducado. Vuelve a escanear el código QR.',
  },
  err_restaurant_inactive: {
    ro: 'Restaurantul nu primește comenzi online acum.',
    en: 'The restaurant is not taking online orders right now.',
    de: 'Das Restaurant nimmt gerade keine Online-Bestellungen an.',
    fr: 'Le restaurant ne prend pas de commandes en ligne pour le moment.',
    it: 'Il ristorante al momento non accetta ordini online.',
    hu: 'Az étterem most nem fogad online rendelést.',
    es: 'El restaurante no acepta pedidos en línea ahora mismo.',
  },
  err_pickup_disabled: {
    ro: 'Comenzile pentru ridicare nu sunt disponibile momentan.',
    en: 'Pickup orders are not available right now.',
    de: 'Abholbestellungen sind gerade nicht verfügbar.',
    fr: 'Les commandes à emporter ne sont pas disponibles pour le moment.',
    it: 'Gli ordini da asporto non sono disponibili al momento.',
    hu: 'Elvitelre most nem lehet rendelni.',
    es: 'Los pedidos para recoger no están disponibles ahora mismo.',
  },
  err_pickup_too_soon: {
    ro: 'Intervalul ales e prea aproape. Alege unul mai târziu.',
    en: 'The chosen time is too soon. Pick a later one.',
    de: 'Die gewählte Zeit ist zu früh. Wähle eine spätere.',
    fr: 'Le créneau choisi est trop proche. Choisissez-en un plus tard.',
    it: 'L’orario scelto è troppo vicino. Scegline uno più tardi.',
    hu: 'A választott időpont túl közeli. Válassz későbbit.',
    es: 'La hora elegida está demasiado cerca. Elige una más tarde.',
  },
  err_pickup_too_far: {
    ro: 'Poți comanda pentru ridicare cel mult cu 24 de ore înainte. Alege un interval mai apropiat.',
    en: 'Pickup can be ordered at most 24 hours ahead. Pick an earlier time.',
    de: 'Abholung ist höchstens 24 Stunden im Voraus möglich. Wähle eine frühere Zeit.',
    fr: 'Le retrait se commande au plus 24 heures à l’avance. Choisissez un créneau plus proche.',
    it: 'Puoi ordinare per l’asporto al massimo 24 ore prima. Scegli un orario più vicino.',
    hu: 'Elvitelre legfeljebb 24 órával előre lehet rendelni. Válassz korábbi időpontot.',
    es: 'Puedes pedir para recoger con un máximo de 24 horas de antelación. Elige una hora más cercana.',
  },
  err_pickup_time_missing: {
    ro: 'Te rog alege un interval de ridicare.',
    en: 'Please choose a pickup time.',
    de: 'Bitte wähle eine Abholzeit.',
    fr: 'Veuillez choisir un créneau de retrait.',
    it: 'Scegli un orario di ritiro.',
    hu: 'Kérjük, válassz átvételi időpontot.',
    es: 'Elige una hora de recogida, por favor.',
  },
  err_name_required: {
    ro: 'Te rog completează numele.',
    en: 'Please enter your name.',
    de: 'Bitte gib deinen Namen ein.',
    fr: 'Veuillez indiquer votre nom.',
    it: 'Inserisci il tuo nome.',
    hu: 'Kérjük, add meg a neved.',
    es: 'Escribe tu nombre, por favor.',
  },
  err_rate_limit_order: {
    ro: 'Prea multe comenzi într-un timp scurt. Reîncearcă în câteva minute.',
    en: 'Too many orders in a short time. Try again in a few minutes.',
    de: 'Zu viele Bestellungen in kurzer Zeit. Versuche es in ein paar Minuten erneut.',
    fr: 'Trop de commandes en peu de temps. Réessayez dans quelques minutes.',
    it: 'Troppi ordini in poco tempo. Riprova tra qualche minuto.',
    hu: 'Túl sok rendelés rövid idő alatt. Próbáld újra néhány perc múlva.',
    es: 'Demasiados pedidos en poco tiempo. Inténtalo de nuevo en unos minutos.',
  },
  err_table_unavailable: {
    ro: 'Masa tocmai a fost rezervată. Alege altă masă liberă.',
    en: 'That table was just booked. Please pick another free table.',
    de: 'Dieser Tisch wurde gerade reserviert. Bitte wähle einen anderen freien Tisch.',
    fr: 'Cette table vient d’être réservée. Choisissez une autre table libre.',
    it: 'Questo tavolo è appena stato prenotato. Scegline un altro libero.',
    hu: 'Ezt az asztalt épp most foglalták le. Válassz másik szabad asztalt.',
    es: 'Esa mesa se acaba de reservar. Elige otra mesa libre.',
  },
  err_rate_limit_reservation: {
    ro: 'Prea multe rezervări într-un interval scurt. Reîncearcă mai târziu.',
    en: 'Too many reservations in a short time. Try again later.',
    de: 'Zu viele Reservierungen in kurzer Zeit. Versuche es später erneut.',
    fr: 'Trop de réservations en peu de temps. Réessayez plus tard.',
    it: 'Troppe prenotazioni in poco tempo. Riprova più tardi.',
    hu: 'Túl sok foglalás rövid idő alatt. Próbáld újra később.',
    es: 'Demasiadas reservas en poco tiempo. Inténtalo más tarde.',
  },
  err_reservation_overlap: {
    ro: 'Intervalul ales se suprapune cu altă rezervare. Alege altă oră.',
    en: 'That time overlaps another reservation. Pick another slot.',
    de: 'Diese Zeit überschneidet sich mit einer anderen Reservierung. Wähle eine andere Uhrzeit.',
    fr: 'Ce créneau chevauche une autre réservation. Choisissez une autre heure.',
    it: 'Questo orario si sovrappone a un’altra prenotazione. Scegli un altro orario.',
    hu: 'Ez az időpont ütközik egy másik foglalással. Válassz másik időpontot.',
    es: 'Esa hora se solapa con otra reserva. Elige otra hora.',
  },
  err_reservation_day_closed: {
    ro: 'Restaurantul e închis în ziua aleasă. Alege altă zi.',
    en: 'The restaurant is closed on the selected day. Pick another day.',
    de: 'Das Restaurant ist am gewählten Tag geschlossen. Wähle einen anderen Tag.',
    fr: 'Le restaurant est fermé ce jour-là. Choisissez un autre jour.',
    it: 'Il ristorante è chiuso nel giorno scelto. Scegli un altro giorno.',
    hu: 'Az étterem a választott napon zárva van. Válassz másik napot.',
    es: 'El restaurante está cerrado ese día. Elige otro día.',
  },
  err_reservation_failed: {
    ro: 'Nu am putut salva rezervarea. Verifică datele și reîncearcă.',
    en: 'Could not save the reservation. Check the details and try again.',
    de: 'Die Reservierung konnte nicht gespeichert werden. Prüfe die Angaben und versuche es erneut.',
    fr: 'Impossible d’enregistrer la réservation. Vérifiez les informations et réessayez.',
    it: 'Impossibile salvare la prenotazione. Controlla i dati e riprova.',
    hu: 'Nem sikerült menteni a foglalást. Ellenőrizd az adatokat, és próbáld újra.',
    es: 'No se pudo guardar la reserva. Revisa los datos e inténtalo de nuevo.',
  },
  err_reservations_off: {
    ro: 'Rezervările nu sunt active pentru acest restaurant.',
    en: 'Reservations are not enabled for this restaurant.',
    de: 'Reservierungen sind für dieses Restaurant nicht aktiviert.',
    fr: 'Les réservations ne sont pas activées pour ce restaurant.',
    it: 'Le prenotazioni non sono attive per questo ristorante.',
    hu: 'Ennél az étteremnél nincs bekapcsolva a foglalás.',
    es: 'Las reservas no están activas en este restaurante.',
  },
  err_invalid_code: {
    ro: 'Cod de confirmare invalid.',
    en: 'Invalid confirmation code.',
    de: 'Ungültiger Bestätigungscode.',
    fr: 'Code de confirmation invalide.',
    it: 'Codice di conferma non valido.',
    hu: 'Érvénytelen visszaigazoló kód.',
    es: 'Código de confirmación no válido.',
  },
  err_module_disabled: {
    ro: 'Această funcție nu este activă la acest local.',
    en: 'This feature is not enabled at this venue.',
    de: 'Diese Funktion ist in diesem Lokal nicht aktiviert.',
    fr: 'Cette fonction n’est pas activée dans cet établissement.',
    it: 'Questa funzione non è attiva in questo locale.',
    hu: 'Ez a funkció ebben a vendéglátóhelyben nincs bekapcsolva.',
    es: 'Esta función no está activa en este local.',
  },
  err_payments_not_ready: {
    ro: 'Localul nu a terminat configurarea plăților online. Cere nota ospătarului.',
    en: 'The venue has not finished setting up online payments. Ask your waiter for the bill.',
    de: 'Das Lokal hat die Online-Zahlung noch nicht fertig eingerichtet. Bitte frag nach der Rechnung.',
    fr: 'L’établissement n’a pas fini de configurer le paiement en ligne. Demandez l’addition au serveur.',
    it: 'Il locale non ha completato la configurazione dei pagamenti online. Chiedi il conto al cameriere.',
    hu: 'A hely még nem állította be az online fizetést. Kérd el a számlát a pincértől.',
    es: 'El local no ha terminado de configurar los pagos en línea. Pide la cuenta al camarero.',
  },
  err_online_pay_off: {
    ro: 'Plata online nu este activată la acest local. Cere nota ospătarului.',
    en: 'Online payment is not enabled at this venue. Ask your waiter for the bill.',
    de: 'Online-Zahlung ist in diesem Lokal nicht aktiviert. Bitte frag nach der Rechnung.',
    fr: 'Le paiement en ligne n’est pas activé dans cet établissement. Demandez l’addition au serveur.',
    it: 'Il pagamento online non è attivo in questo locale. Chiedi il conto al cameriere.',
    hu: 'Ebben a vendéglátóhelyben nincs online fizetés. Kérd el a számlát a pincértől.',
    es: 'El pago en línea no está activo en este local. Pide la cuenta al camarero.',
  },
  err_split_off: {
    ro: 'Împărțirea notei nu este disponibilă la acest local.',
    en: 'Splitting the bill is not available at this venue.',
    de: 'Getrennt zahlen ist in diesem Lokal nicht möglich.',
    fr: 'Le partage de l’addition n’est pas disponible dans cet établissement.',
    it: 'La divisione del conto non è disponibile in questo locale.',
    hu: 'Ebben a vendéglátóhelyben nem lehet megosztani a számlát.',
    es: 'Dividir la cuenta no está disponible en este local.',
  },
  err_nothing_to_pay: {
    ro: 'Nu există comenzi de plătit — probabil nota a fost deja achitată.',
    en: 'There is nothing to pay — the bill has probably been settled already.',
    de: 'Es gibt nichts zu bezahlen – die Rechnung wurde wohl schon beglichen.',
    fr: 'Il n’y a rien à payer — l’addition a sans doute déjà été réglée.',
    it: 'Non c’è nulla da pagare: probabilmente il conto è già stato saldato.',
    hu: 'Nincs mit fizetni – a számlát valószínűleg már rendezték.',
    es: 'No hay nada que pagar: probablemente la cuenta ya está saldada.',
  },
  err_currency_not_supported: {
    ro: 'Plata online e disponibilă doar pentru meniuri în lei. Cere nota ospătarului.',
    en: 'Online payment is only available for menus priced in lei. Ask your waiter for the bill.',
    de: 'Online-Zahlung gibt es nur für Menüs in Lei. Bitte frag nach der Rechnung.',
    fr: 'Le paiement en ligne n’est disponible que pour les menus en lei. Demandez l’addition au serveur.',
    it: 'Il pagamento online è disponibile solo per menu in lei. Chiedi il conto al cameriere.',
    hu: 'Online fizetés csak lejben árazott menünél lehetséges. Kérd el a számlát a pincértől.',
    es: 'El pago en línea solo está disponible para menús en lei. Pide la cuenta al camarero.',
  },
  err_items_already_claimed: {
    ro: 'Cineva de la masă plătește deja o parte din aceste produse. Alege altele sau reîncearcă.',
    en: 'Someone at the table is already paying for some of these items. Choose others or try again.',
    de: 'Jemand am Tisch bezahlt bereits einige dieser Artikel. Wähle andere oder versuche es erneut.',
    fr: 'Quelqu’un à la table paie déjà une partie de ces articles. Choisissez-en d’autres ou réessayez.',
    it: 'Qualcuno al tavolo sta già pagando alcuni di questi prodotti. Scegline altri o riprova.',
    hu: 'Valaki az asztalnál már fizet néhány tételért. Válassz másikat, vagy próbáld újra.',
    es: 'Alguien en la mesa ya está pagando parte de estos productos. Elige otros o inténtalo de nuevo.',
  },
  err_bill_changed: {
    ro: 'Nota s-a schimbat între timp — redeschide împărțirea notei.',
    en: 'The bill has changed in the meantime — reopen bill splitting.',
    de: 'Die Rechnung hat sich inzwischen geändert – öffne das Aufteilen erneut.',
    fr: 'L’addition a changé entre-temps — rouvrez le partage.',
    it: 'Il conto è cambiato nel frattempo: riapri la divisione del conto.',
    hu: 'A számla időközben megváltozott – nyisd meg újra a megosztást.',
    es: 'La cuenta ha cambiado mientras tanto: vuelve a abrir la división.',
  },
  err_amount_mismatch: {
    ro: 'Suma nu mai corespunde cu nota. Reîncarcă și încearcă din nou.',
    en: 'The amount no longer matches the bill. Reload and try again.',
    de: 'Der Betrag stimmt nicht mehr mit der Rechnung überein. Lade neu und versuche es erneut.',
    fr: 'Le montant ne correspond plus à l’addition. Rechargez et réessayez.',
    it: 'L’importo non corrisponde più al conto. Ricarica e riprova.',
    hu: 'Az összeg már nem egyezik a számlával. Töltsd újra, és próbáld újra.',
    es: 'El importe ya no coincide con la cuenta. Recarga e inténtalo de nuevo.',
  },
  err_payment_failed: {
    ro: 'Plata nu a putut fi inițiată.',
    en: 'The payment could not be started.',
    de: 'Die Zahlung konnte nicht gestartet werden.',
    fr: 'Le paiement n’a pas pu être lancé.',
    it: 'Non è stato possibile avviare il pagamento.',
    hu: 'A fizetést nem sikerült elindítani.',
    es: 'No se pudo iniciar el pago.',
  },
  err_bill_load_failed: {
    ro: 'Nota nu a putut fi încărcată.',
    en: 'The bill could not be loaded.',
    de: 'Die Rechnung konnte nicht geladen werden.',
    fr: 'L’addition n’a pas pu être chargée.',
    it: 'Non è stato possibile caricare il conto.',
    hu: 'A számlát nem sikerült betölteni.',
    es: 'No se pudo cargar la cuenta.',
  },
  // ── Alergeni (Reg. UE 1169/2011, denumirile oficiale) ──
  allergen_gluten: {
    ro: 'Gluten',
    en: 'Gluten',
    de: 'Gluten',
    fr: 'Gluten',
    it: 'Glutine',
    hu: 'Glutén',
    es: 'Gluten',
  },
  allergen_crustacee: {
    ro: 'Crustacee',
    en: 'Crustaceans',
    de: 'Krebstiere',
    fr: 'Crustacés',
    it: 'Crostacei',
    hu: 'Rákfélék',
    es: 'Crustáceos',
  },
  allergen_oua: {
    ro: 'Ouă',
    en: 'Eggs',
    de: 'Eier',
    fr: 'Œufs',
    it: 'Uova',
    hu: 'Tojás',
    es: 'Huevos',
  },
  allergen_peste: {
    ro: 'Pește',
    en: 'Fish',
    de: 'Fisch',
    fr: 'Poisson',
    it: 'Pesce',
    hu: 'Hal',
    es: 'Pescado',
  },
  allergen_arahide: {
    ro: 'Arahide',
    en: 'Peanuts',
    de: 'Erdnüsse',
    fr: 'Arachides',
    it: 'Arachidi',
    hu: 'Földimogyoró',
    es: 'Cacahuetes',
  },
  allergen_soia: {
    ro: 'Soia',
    en: 'Soybeans',
    de: 'Soja',
    fr: 'Soja',
    it: 'Soia',
    hu: 'Szója',
    es: 'Soja',
  },
  allergen_lapte: {
    ro: 'Lapte',
    en: 'Milk',
    de: 'Milch',
    fr: 'Lait',
    it: 'Latte',
    hu: 'Tej',
    es: 'Leche',
  },
  allergen_nuci: {
    ro: 'Nuci',
    en: 'Nuts',
    de: 'Schalenfrüchte',
    fr: 'Fruits à coque',
    it: 'Frutta a guscio',
    hu: 'Diófélék',
    es: 'Frutos de cáscara',
  },
  allergen_telina: {
    ro: 'Țelină',
    en: 'Celery',
    de: 'Sellerie',
    fr: 'Céleri',
    it: 'Sedano',
    hu: 'Zeller',
    es: 'Apio',
  },
  allergen_mustar: {
    ro: 'Muștar',
    en: 'Mustard',
    de: 'Senf',
    fr: 'Moutarde',
    it: 'Senape',
    hu: 'Mustár',
    es: 'Mostaza',
  },
  allergen_susan: {
    ro: 'Susan',
    en: 'Sesame',
    de: 'Sesam',
    fr: 'Sésame',
    it: 'Sesamo',
    hu: 'Szezámmag',
    es: 'Sésamo',
  },
  allergen_sulfiti: {
    ro: 'Sulfiți',
    en: 'Sulphites',
    de: 'Sulfite',
    fr: 'Sulfites',
    it: 'Solfiti',
    hu: 'Szulfitok',
    es: 'Sulfitos',
  },
  allergen_lupin: {
    ro: 'Lupin',
    en: 'Lupin',
    de: 'Lupinen',
    fr: 'Lupin',
    it: 'Lupini',
    hu: 'Csillagfürt',
    es: 'Altramuces',
  },
  allergen_molusce: {
    ro: 'Moluște',
    en: 'Molluscs',
    de: 'Weichtiere',
    fr: 'Mollusques',
    it: 'Molluschi',
    hu: 'Puhatestűek',
    es: 'Moluscos',
  },
  // ── Etichete dietetice ──
  diet_signature: {
    ro: 'Signature',
    en: 'Signature',
    de: 'Signature',
    fr: 'Signature',
    it: 'Signature',
    hu: 'Signature',
    es: 'Signature',
  },
  diet_nou: {
    ro: 'Nou',
    en: 'New',
    de: 'Neu',
    fr: 'Nouveau',
    it: 'Novità',
    hu: 'Új',
    es: 'Nuevo',
  },
  diet_vegetarian: {
    ro: 'Vegetarian',
    en: 'Vegetarian',
    de: 'Vegetarisch',
    fr: 'Végétarien',
    it: 'Vegetariano',
    hu: 'Vegetáriánus',
    es: 'Vegetariano',
  },
  diet_vegan: {
    ro: 'Vegan',
    en: 'Vegan',
    de: 'Vegan',
    fr: 'Végan',
    it: 'Vegano',
    hu: 'Vegán',
    es: 'Vegano',
  },
  diet_fara_gluten: {
    ro: 'Fără gluten',
    en: 'Gluten-free',
    de: 'Glutenfrei',
    fr: 'Sans gluten',
    it: 'Senza glutine',
    hu: 'Gluténmentes',
    es: 'Sin gluten',
  },
  diet_fara_lactoza: {
    ro: 'Fără lactoză',
    en: 'Lactose-free',
    de: 'Laktosefrei',
    fr: 'Sans lactose',
    it: 'Senza lattosio',
    hu: 'Laktózmentes',
    es: 'Sin lactosa',
  },
  diet_picant: {
    ro: 'Picant',
    en: 'Spicy',
    de: 'Scharf',
    fr: 'Épicé',
    it: 'Piccante',
    hu: 'Csípős',
    es: 'Picante',
  },
  diet_raw: {
    ro: 'Raw',
    en: 'Raw',
    de: 'Roh',
    fr: 'Cru',
    it: 'Crudo',
    hu: 'Nyers',
    es: 'Crudo',
  },
  // ── Grupuri de opțiuni (oglinda modifierGroupHint) ──
  mod_choose_exact: {
    ro: 'Alege exact {n}',
    en: 'Choose exactly {n}',
    de: 'Wähle genau {n}',
    fr: 'Choisissez exactement {n}',
    it: 'Scegli esattamente {n}',
    hu: 'Válassz pontosan {n} db-ot',
    es: 'Elige exactamente {n}',
  },
  mod_choose_between: {
    ro: 'Alege între {min} și {max}',
    en: 'Choose between {min} and {max}',
    de: 'Wähle zwischen {min} und {max}',
    fr: 'Choisissez entre {min} et {max}',
    it: 'Scegli tra {min} e {max}',
    hu: 'Válassz {min}–{max} db-ot',
    es: 'Elige entre {min} y {max}',
  },
  mod_choose_at_least: {
    ro: 'Alege cel puțin {n}',
    en: 'Choose at least {n}',
    de: 'Wähle mindestens {n}',
    fr: 'Choisissez au moins {n}',
    it: 'Scegli almeno {n}',
    hu: 'Válassz legalább {n} db-ot',
    es: 'Elige al menos {n}',
  },
  mod_choose_max: {
    ro: 'Maxim {n}',
    en: 'Up to {n}',
    de: 'Höchstens {n}',
    fr: '{n} maximum',
    it: 'Massimo {n}',
    hu: 'Legfeljebb {n}',
    es: 'Máximo {n}',
  },
} as const
