// ─────────────────────────────────────────────────────────────
// guestStrings — textele fluxului OASPETELUI (coș, fișa produsului,
// urmărirea comenzii, plata la masă, împărțirea notei, ridicare, rezervare,
// ecranul de plată, erorile de server traduse) în cele 7 limbi ale meniului.
//
// Intră în PUBLIC_MENU_STRINGS prin spread (publicMenuStrings.ts), deci se
// citesc cu același `T(lang, key)`. Fișier separat ca tabela de bază să nu
// devină un punct de conflict permanent. Modul FĂRĂ importuri: ajunge doar în
// chunk-urile de meniu (aceeași disciplină ca publicMenuStrings, OPT-11).
//
// Reguli (clichet în src/lib/__tests__/guestI18n.test.ts):
//   • fiecare cheie are TOATE cele 7 limbi, ne-goale;
//   • substituțiile `{nume}` sunt IDENTICE în toate limbile (Tf le înlocuiește);
//   • pe Planul 2 Menuvia nu încasează nimic — niciun text de aici nu promite
//     „plătit" în afara ramurilor care chiar sunt plăți (online / `paid`).
// ─────────────────────────────────────────────────────────────

export const GUEST_STRINGS = {
  // ── Urmărirea comenzii (OrderTracker + ActiveOrdersBanner) ──
  ot_step_new: {
    ro: 'Trimisă',
    en: 'Sent',
    de: 'Gesendet',
    fr: 'Envoyée',
    it: 'Inviato',
    hu: 'Elküldve',
    es: 'Enviado',
  },
  ot_step_confirmed: {
    ro: 'Confirmată',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  ot_step_preparing: {
    ro: 'În preparare',
    en: 'Being prepared',
    de: 'In Zubereitung',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'En preparación',
  },
  ot_step_ready: {
    ro: 'Gata de servit',
    en: 'Ready to serve',
    de: 'Servierbereit',
    fr: 'Prête à servir',
    it: 'Pronto da servire',
    hu: 'Tálalásra kész',
    es: 'Listo para servir',
  },
  ot_step_served: {
    ro: 'Servită',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  ot_sent_title: {
    ro: 'Comanda a fost trimisă',
    en: 'Your order has been sent',
    de: 'Deine Bestellung wurde gesendet',
    fr: 'Votre commande a été envoyée',
    it: 'Il tuo ordine è stato inviato',
    hu: 'A rendelésedet elküldtük',
    es: 'Tu pedido ha sido enviado',
  },
  ot_kitchen_received: {
    ro: 'Bucătăria a primit comanda.',
    en: 'The kitchen has received your order.',
    de: 'Die Küche hat deine Bestellung erhalten.',
    fr: 'La cuisine a reçu votre commande.',
    it: 'La cucina ha ricevuto il tuo ordine.',
    hu: 'A konyha megkapta a rendelésedet.',
    es: 'La cocina ha recibido tu pedido.',
  },
  ot_limited: {
    ro: 'Urmărirea comenzii nu mai este disponibilă complet.',
    en: 'Full order tracking is no longer available.',
    de: 'Die vollständige Bestellverfolgung ist nicht mehr verfügbar.',
    fr: 'Le suivi complet de la commande n’est plus disponible.',
    it: 'Il monitoraggio completo dell’ordine non è più disponibile.',
    hu: 'A rendelés teljes követése már nem érhető el.',
    es: 'El seguimiento completo del pedido ya no está disponible.',
  },
  ask_staff: {
    ro: 'Te rugăm să întrebi personalul.',
    en: 'Please ask the staff.',
    de: 'Bitte frag das Personal.',
    fr: 'Merci de demander au personnel.',
    it: 'Chiedi al personale, per favore.',
    hu: 'Kérjük, kérdezd meg a személyzetet.',
    es: 'Pregunta al personal, por favor.',
  },
  ot_cancelled: {
    ro: 'Comanda a fost anulată',
    en: 'Your order was cancelled',
    de: 'Deine Bestellung wurde storniert',
    fr: 'Votre commande a été annulée',
    it: 'Il tuo ordine è stato annullato',
    hu: 'A rendelésedet törölték',
    es: 'Tu pedido ha sido cancelado',
  },
  ot_now: {
    ro: 'Acum',
    en: 'Now',
    de: 'Jetzt',
    fr: 'Maintenant',
    it: 'Ora',
    hu: 'Most',
    es: 'Ahora',
  },
  add_more_items: {
    ro: '+ Adaugă produse',
    en: '+ Add more items',
    de: '+ Weitere Artikel hinzufügen',
    fr: '+ Ajouter des articles',
    it: '+ Aggiungi prodotti',
    hu: '+ További tételek',
    es: '+ Añadir productos',
  },
  ot_new_order: {
    ro: 'Comandă nouă',
    en: 'New order',
    de: 'Neue Bestellung',
    fr: 'Nouvelle commande',
    it: 'Nuovo ordine',
    hu: 'Új rendelés',
    es: 'Nuevo pedido',
  },
  ot_close_session: {
    ro: 'Închide sesiunea',
    en: 'Close session',
    de: 'Sitzung beenden',
    fr: 'Fermer la session',
    it: 'Chiudi la sessione',
    hu: 'Munkamenet bezárása',
    es: 'Cerrar la sesión',
  },
  ot_session_total: {
    ro: 'Total sesiune:',
    en: 'Session total:',
    de: 'Summe der Sitzung:',
    fr: 'Total de la session :',
    it: 'Totale della sessione:',
    hu: 'Munkamenet összesen:',
    es: 'Total de la sesión:',
  },
  order_one: {
    ro: 'comandă',
    en: 'order',
    de: 'Bestellung',
    fr: 'commande',
    it: 'ordine',
    hu: 'rendelés',
    es: 'pedido',
  },
  order_many: {
    ro: 'comenzi',
    en: 'orders',
    de: 'Bestellungen',
    fr: 'commandes',
    it: 'ordini',
    hu: 'rendelés',
    es: 'pedidos',
  },
  total_suffix: {
    ro: 'total',
    en: 'total',
    de: 'gesamt',
    fr: 'au total',
    it: 'in totale',
    hu: 'összesen',
    es: 'en total',
  },
  active_one: {
    ro: 'activă',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivo',
    hu: 'aktív',
    es: 'activo',
  },
  active_many: {
    ro: 'active',
    en: 'active',
    de: 'aktiv',
    fr: 'en cours',
    it: 'attivi',
    hu: 'aktív',
    es: 'activos',
  },
  order_hash: {
    ro: 'Comanda #',
    en: 'Order #',
    de: 'Bestellung #',
    fr: 'Commande n° ',
    it: 'Ordine #',
    hu: 'Rendelés #',
    es: 'Pedido #',
  },
  st_new: {
    ro: 'Primit',
    en: 'Received',
    de: 'Eingegangen',
    fr: 'Reçue',
    it: 'Ricevuto',
    hu: 'Beérkezett',
    es: 'Recibido',
  },
  st_confirmed: {
    ro: 'Confirmat',
    en: 'Confirmed',
    de: 'Bestätigt',
    fr: 'Confirmée',
    it: 'Confermato',
    hu: 'Visszaigazolva',
    es: 'Confirmado',
  },
  st_preparing: {
    ro: 'Se prepară',
    en: 'Preparing',
    de: 'Wird zubereitet',
    fr: 'En préparation',
    it: 'In preparazione',
    hu: 'Készül',
    es: 'Preparándose',
  },
  st_served: {
    ro: 'Servit',
    en: 'Served',
    de: 'Serviert',
    fr: 'Servie',
    it: 'Servito',
    hu: 'Felszolgálva',
    es: 'Servido',
  },
  st_paid: {
    ro: 'Plătit',
    en: 'Paid',
    de: 'Bezahlt',
    fr: 'Payée',
    it: 'Pagato',
    hu: 'Fizetve',
    es: 'Pagado',
  },
  st_closed: {
    ro: 'Închisă',
    en: 'Closed',
    de: 'Abgeschlossen',
    fr: 'Clôturée',
    it: 'Chiuso',
    hu: 'Lezárva',
    es: 'Cerrado',
  },
  st_cancelled: {
    ro: 'Anulat',
    en: 'Cancelled',
    de: 'Storniert',
    fr: 'Annulée',
    it: 'Annullato',
    hu: 'Törölve',
    es: 'Cancelado',
  },

  // ── Ecranul „Plată confirmată" + feedback (PaymentConfirmedScreen) ──
  paid_title: {
    ro: 'Plată confirmată!',
    en: 'Payment confirmed!',
    de: 'Zahlung bestätigt!',
    fr: 'Paiement confirmé !',
    it: 'Pagamento confermato!',
    hu: 'Fizetés visszaigazolva!',
    es: '¡Pago confirmado!',
  },
  paid_subtitle: {
    ro: 'Personalul restaurantului știe deja că masa a fost plătită.\nÎți mulțumim pentru vizită!',
    en: 'The restaurant staff already knows your table has been paid.\nThank you for your visit!',
    de: 'Das Restaurantpersonal weiß bereits, dass dein Tisch bezahlt ist.\nDanke für deinen Besuch!',
    fr: 'Le personnel du restaurant sait déjà que votre table a été réglée.\nMerci de votre visite !',
    it: 'Il personale del ristorante sa già che il tavolo è stato pagato.\nGrazie per la visita!',
    hu: 'Az étterem személyzete már tudja, hogy az asztalt kifizették.\nKöszönjük a látogatást!',
    es: 'El personal del restaurante ya sabe que la mesa está pagada.\n¡Gracias por tu visita!',
  },
  subtotal: {
    ro: 'Subtotal',
    en: 'Subtotal',
    de: 'Zwischensumme',
    fr: 'Sous-total',
    it: 'Subtotale',
    hu: 'Részösszeg',
    es: 'Subtotal',
  },
  tip: {
    ro: 'Bacșiș',
    en: 'Tip',
    de: 'Trinkgeld',
    fr: 'Pourboire',
    it: 'Mancia',
    hu: 'Borravaló',
    es: 'Propina',
  },
  fast_pay_fee: {
    ro: 'Comision plată rapidă',
    en: 'Fast pay fee',
    de: 'Gebühr für Schnellzahlung',
    fr: 'Frais de paiement rapide',
    it: 'Commissione pagamento rapido',
    hu: 'Gyorsfizetési díj',
    es: 'Comisión de pago rápido',
  },
  need_fiscal_receipt: {
    ro: 'Am nevoie de bonul fiscal',
    en: 'I need the fiscal receipt',
    de: 'Ich brauche den Kassenbon',
    fr: 'J’ai besoin du ticket de caisse',
    it: 'Mi serve lo scontrino fiscale',
    hu: 'Kérem a nyugtát',
    es: 'Necesito el ticket fiscal',
  },
  fiscal_requested: {
    ro: 'Bonul fiscal a fost cerut',
    en: 'Fiscal receipt requested',
    de: 'Kassenbon angefordert',
    fr: 'Ticket de caisse demandé',
    it: 'Scontrino fiscale richiesto',
    hu: 'Nyugta kérve',
    es: 'Ticket fiscal solicitado',
  },
  powered_by: {
    ro: 'Realizat cu',
    en: 'Powered by',
    de: 'Bereitgestellt von',
    fr: 'Propulsé par',
    it: 'Realizzato con',
    hu: 'Készítette:',
    es: 'Con la tecnología de',
  },
  fb_title: {
    ro: 'Opinia ta contează',
    en: 'Your opinion matters',
    de: 'Deine Meinung zählt',
    fr: 'Votre avis compte',
    it: 'La tua opinione conta',
    hu: 'Számít a véleményed',
    es: 'Tu opinión importa',
  },
  fb_thanks: {
    ro: 'Îți mulțumim pentru feedback',
    en: 'Thank you for your feedback',
    de: 'Danke für dein Feedback',
    fr: 'Merci pour votre avis',
    it: 'Grazie per il tuo feedback',
    hu: 'Köszönjük a visszajelzést',
    es: 'Gracias por tu opinión',
  },
  fb_ask_payment: {
    ro: 'Cum a fost experiența de plată?',
    en: 'How was the payment experience?',
    de: 'Wie war das Bezahlen?',
    fr: 'Comment s’est passé le paiement ?',
    it: 'Com’è andato il pagamento?',
    hu: 'Milyen volt a fizetés?',
    es: '¿Qué tal fue el pago?',
  },
  fb_ask_service: {
    ro: 'Cum a fost servirea?',
    en: 'How was the service?',
    de: 'Wie war der Service?',
    fr: 'Comment était le service ?',
    it: 'Com’è stato il servizio?',
    hu: 'Milyen volt a kiszolgálás?',
    es: '¿Qué tal fue el servicio?',
  },
  fb_ask_food: {
    ro: 'Cum a fost mâncarea?',
    en: 'How was the food?',
    de: 'Wie war das Essen?',
    fr: 'Comment était le repas ?',
    it: 'Com’era il cibo?',
    hu: 'Milyen volt az étel?',
    es: '¿Qué tal estuvo la comida?',
  },
  fb_negative: {
    ro: 'Ne pare rău. Ce putem îmbunătăți?',
    en: 'We are sorry. What can we improve?',
    de: 'Das tut uns leid. Was können wir besser machen?',
    fr: 'Nous sommes désolés. Que pouvons-nous améliorer ?',
    it: 'Ci dispiace. Cosa possiamo migliorare?',
    hu: 'Sajnáljuk. Min javíthatnánk?',
    es: 'Lo sentimos. ¿Qué podemos mejorar?',
  },
  fb_negative_placeholder: {
    ro: 'Scrie-ne aici...',
    en: 'Write to us here...',
    de: 'Schreib uns hier...',
    fr: 'Écrivez-nous ici...',
    it: 'Scrivici qui...',
    hu: 'Írj nekünk ide...',
    es: 'Escríbenos aquí...',
  },
  fb_google_text: {
    ro: 'Spune-le și altora despre experiența ta la',
    en: 'Tell others about your experience at',
    de: 'Erzähl anderen von deinem Besuch bei',
    fr: 'Partagez votre expérience chez',
    it: 'Racconta agli altri la tua esperienza da',
    hu: 'Meséld el másoknak is az élményed itt:',
    es: 'Cuéntales a otros tu experiencia en',
  },
  fb_google_button: {
    ro: 'Scrie o recenzie pe Google',
    en: 'Write a Google review',
    de: 'Google-Bewertung schreiben',
    fr: 'Laisser un avis Google',
    it: 'Scrivi una recensione su Google',
    hu: 'Írj értékelést a Google-on',
    es: 'Escribe una reseña en Google',
  },
  fb_thumb_up: {
    ro: 'Bine',
    en: 'Good',
    de: 'Gut',
    fr: 'Bien',
    it: 'Bene',
    hu: 'Jó',
    es: 'Bien',
  },
  fb_thumb_down: {
    ro: 'Nu prea bine',
    en: 'Not so good',
    de: 'Nicht so gut',
    fr: 'Pas terrible',
    it: 'Non molto bene',
    hu: 'Nem túl jó',
    es: 'No muy bien',
  },
  fb_stars: {
    ro: '{n} stele',
    en: '{n} stars',
    de: '{n} Sterne',
    fr: '{n} étoiles',
    it: '{n} stelle',
    hu: '{n} csillag',
    es: '{n} estrellas',
  },
  // ── Erori de server traduse (describeGuestError, lib/guestErrors.ts) ──
  err_generic: {
    ro: 'A apărut o eroare. Încearcă din nou.',
    en: 'Something went wrong. Please try again.',
    de: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
    fr: 'Une erreur s’est produite. Veuillez réessayer.',
    it: 'Si è verificato un errore. Riprova.',
    hu: 'Hiba történt. Kérjük, próbáld újra.',
    es: 'Algo salió mal. Inténtalo de nuevo.',
  },
  err_network: {
    ro: 'Conexiune slabă. Verifică internetul și încearcă din nou.',
    en: 'Weak connection. Check your internet and try again.',
    de: 'Schwache Verbindung. Prüfe deine Internetverbindung und versuche es erneut.',
    fr: 'Connexion faible. Vérifiez votre connexion internet et réessayez.',
    it: 'Connessione debole. Controlla internet e riprova.',
    hu: 'Gyenge kapcsolat. Ellenőrizd az internetet, és próbáld újra.',
    es: 'Conexión débil. Revisa tu conexión a internet e inténtalo de nuevo.',
  },
  err_order_not_sent: {
    ro: 'Comanda nu s-a trimis. Încearcă din nou.',
    en: 'Your order was not sent. Please try again.',
    de: 'Deine Bestellung wurde nicht gesendet. Bitte versuche es erneut.',
    fr: 'Votre commande n’a pas été envoyée. Veuillez réessayer.',
    it: 'L’ordine non è stato inviato. Riprova.',
    hu: 'A rendelés nem ment el. Kérjük, próbáld újra.',
    es: 'Tu pedido no se ha enviado. Inténtalo de nuevo.',
  },
  err_order_not_sent_network: {
    ro: 'Comanda nu s-a trimis — conexiune slabă. Verifică internetul și încearcă din nou.',
    en: 'Your order was not sent — weak connection. Check your internet and try again.',
    de: 'Deine Bestellung wurde nicht gesendet – schwache Verbindung. Prüfe dein Internet und versuche es erneut.',
    fr: 'Votre commande n’a pas été envoyée — connexion faible. Vérifiez votre connexion et réessayez.',
    it: 'L’ordine non è stato inviato: connessione debole. Controlla internet e riprova.',
    hu: 'A rendelés nem ment el – gyenge kapcsolat. Ellenőrizd az internetet, és próbáld újra.',
    es: 'Tu pedido no se ha enviado: conexión débil. Revisa internet e inténtalo de nuevo.',
  },
  err_missing_required_group: {
    ro: 'Un produs din coș are opțiuni obligatorii neselectate. Deschide-l și alege opțiunile.',
    en: 'An item in your cart has required options not selected. Open it and choose them.',
    de: 'Bei einem Artikel im Warenkorb fehlen Pflichtoptionen. Öffne ihn und wähle sie aus.',
    fr: 'Un article du panier a des options obligatoires non choisies. Ouvrez-le pour les choisir.',
    it: 'Un prodotto nel carrello ha opzioni obbligatorie non scelte. Aprilo e sceglile.',
    hu: 'A kosár egyik tételénél nincs kiválasztva kötelező opció. Nyisd meg, és válassz.',
    es: 'Un producto del carrito tiene opciones obligatorias sin elegir. Ábrelo y elígelas.',
  },
  err_product_unavailable: {
    ro: 'Un produs din coș nu mai este disponibil. Scoate-l și încearcă din nou.',
    en: 'An item in your cart is no longer available. Remove it and try again.',
    de: 'Ein Artikel im Warenkorb ist nicht mehr verfügbar. Entferne ihn und versuche es erneut.',
    fr: 'Un article du panier n’est plus disponible. Retirez-le et réessayez.',
    it: 'Un prodotto nel carrello non è più disponibile. Rimuovilo e riprova.',
    hu: 'A kosár egyik tétele már nem elérhető. Vedd ki, és próbáld újra.',
    es: 'Un producto del carrito ya no está disponible. Quítalo e inténtalo de nuevo.',
  },
  err_invalid_quantity: {
    ro: 'Cantitate invalidă — maximum 20 bucăți pe produs.',
    en: 'Invalid quantity — maximum 20 per item.',
    de: 'Ungültige Menge – höchstens 20 pro Artikel.',
    fr: 'Quantité invalide — 20 maximum par article.',
    it: 'Quantità non valida: massimo 20 per prodotto.',
    hu: 'Érvénytelen mennyiség – tételenként legfeljebb 20.',
    es: 'Cantidad no válida: máximo 20 por producto.',
  },
  err_too_many_items: {
    ro: 'Comanda are prea multe produse (maximum 30). Trimite restul într-o comandă separată.',
    en: 'Your order has too many items (maximum 30). Send the rest in a separate order.',
    de: 'Deine Bestellung hat zu viele Artikel (höchstens 30). Sende den Rest in einer weiteren Bestellung.',
    fr: 'Votre commande contient trop d’articles (30 maximum). Envoyez le reste dans une autre commande.',
    it: 'L’ordine ha troppi prodotti (massimo 30). Invia il resto in un ordine separato.',
    hu: 'Túl sok tétel van a rendelésben (legfeljebb 30). A többit küldd külön rendelésben.',
    es: 'Tu pedido tiene demasiados productos (máximo 30). Envía el resto en otro pedido.',
  },
  err_no_items: {
    ro: 'Coșul e gol. Adaugă produse din meniu.',
    en: 'Your cart is empty. Add items from the menu.',
    de: 'Dein Warenkorb ist leer. Füge Artikel aus dem Menü hinzu.',
    fr: 'Votre panier est vide. Ajoutez des articles depuis le menu.',
    it: 'Il carrello è vuoto. Aggiungi prodotti dal menu.',
    hu: 'A kosár üres. Adj hozzá tételeket a menüből.',
    es: 'Tu carrito está vacío. Añade productos del menú.',
  },
  err_invalid_options: {
    ro: 'Opțiunile unui produs nu mai sunt valide. Scoate produsul din coș și adaugă-l din nou.',
    en: 'The options of an item are no longer valid. Remove it from the cart and add it again.',
    de: 'Die Optionen eines Artikels sind nicht mehr gültig. Entferne ihn und füge ihn erneut hinzu.',
    fr: 'Les options d’un article ne sont plus valides. Retirez-le du panier et ajoutez-le à nouveau.',
    it: 'Le opzioni di un prodotto non sono più valide. Rimuovilo dal carrello e aggiungilo di nuovo.',
    hu: 'Egy tétel opciói már nem érvényesek. Vedd ki a kosárból, és add hozzá újra.',
    es: 'Las opciones de un producto ya no son válidas. Quítalo del carrito y vuelve a añadirlo.',
  },
  err_notes_too_long: {
    ro: 'Mențiunea e prea lungă. Scurteaz-o și încearcă din nou.',
    en: 'Your note is too long. Shorten it and try again.',
    de: 'Deine Anmerkung ist zu lang. Kürze sie und versuche es erneut.',
    fr: 'Votre remarque est trop longue. Raccourcissez-la et réessayez.',
    it: 'La nota è troppo lunga. Accorciala e riprova.',
    hu: 'A megjegyzés túl hosszú. Rövidítsd le, és próbáld újra.',
    es: 'Tu nota es demasiado larga. Acórtala e inténtalo de nuevo.',
  },
  err_session_closed: {
    ro: 'Masa a fost închisă sau sesiunea a expirat. Scanează din nou codul QR.',
    en: 'The table was closed or the session expired. Scan the QR code again.',
    de: 'Der Tisch wurde geschlossen oder die Sitzung ist abgelaufen. Scanne den QR-Code erneut.',
    fr: 'La table a été clôturée ou la session a expiré. Scannez à nouveau le QR code.',
    it: 'Il tavolo è stato chiuso o la sessione è scaduta. Scansiona di nuovo il codice QR.',
    hu: 'Az asztalt lezárták, vagy lejárt a munkamenet. Olvasd be újra a QR-kódot.',
    es: 'La mesa se ha cerrado o la sesión ha caducado. Vuelve a escanear el código QR.',
  },
  err_restaurant_inactive: {
    ro: 'Restaurantul nu primește comenzi online acum.',
    en: 'The restaurant is not taking online orders right now.',
    de: 'Das Restaurant nimmt gerade keine Online-Bestellungen an.',
    fr: 'Le restaurant ne prend pas de commandes en ligne pour le moment.',
    it: 'Il ristorante al momento non accetta ordini online.',
    hu: 'Az étterem most nem fogad online rendelést.',
    es: 'El restaurante no acepta pedidos en línea ahora mismo.',
  },
  err_pickup_disabled: {
    ro: 'Comenzile pentru ridicare nu sunt disponibile momentan.',
    en: 'Pickup orders are not available right now.',
    de: 'Abholbestellungen sind gerade nicht verfügbar.',
    fr: 'Les commandes à emporter ne sont pas disponibles pour le moment.',
    it: 'Gli ordini da asporto non sono disponibili al momento.',
    hu: 'Elvitelre most nem lehet rendelni.',
    es: 'Los pedidos para recoger no están disponibles ahora mismo.',
  },
  err_pickup_too_soon: {
    ro: 'Intervalul ales e prea aproape. Alege unul mai târziu.',
    en: 'The chosen time is too soon. Pick a later one.',
    de: 'Die gewählte Zeit ist zu früh. Wähle eine spätere.',
    fr: 'Le créneau choisi est trop proche. Choisissez-en un plus tard.',
    it: 'L’orario scelto è troppo vicino. Scegline uno più tardi.',
    hu: 'A választott időpont túl közeli. Válassz későbbit.',
    es: 'La hora elegida está demasiado cerca. Elige una más tarde.',
  },
  err_pickup_too_far: {
    ro: 'Poți comanda pentru ridicare cel mult cu 24 de ore înainte. Alege un interval mai apropiat.',
    en: 'Pickup can be ordered at most 24 hours ahead. Pick an earlier time.',
    de: 'Abholung ist höchstens 24 Stunden im Voraus möglich. Wähle eine frühere Zeit.',
    fr: 'Le retrait se commande au plus 24 heures à l’avance. Choisissez un créneau plus proche.',
    it: 'Puoi ordinare per l’asporto al massimo 24 ore prima. Scegli un orario più vicino.',
    hu: 'Elvitelre legfeljebb 24 órával előre lehet rendelni. Válassz korábbi időpontot.',
    es: 'Puedes pedir para recoger con un máximo de 24 horas de antelación. Elige una hora más cercana.',
  },
  err_pickup_time_missing: {
    ro: 'Te rog alege un interval de ridicare.',
    en: 'Please choose a pickup time.',
    de: 'Bitte wähle eine Abholzeit.',
    fr: 'Veuillez choisir un créneau de retrait.',
    it: 'Scegli un orario di ritiro.',
    hu: 'Kérjük, válassz átvételi időpontot.',
    es: 'Elige una hora de recogida, por favor.',
  },
  err_name_required: {
    ro: 'Te rog completează numele.',
    en: 'Please enter your name.',
    de: 'Bitte gib deinen Namen ein.',
    fr: 'Veuillez indiquer votre nom.',
    it: 'Inserisci il tuo nome.',
    hu: 'Kérjük, add meg a neved.',
    es: 'Escribe tu nombre, por favor.',
  },
  err_rate_limit_order: {
    ro: 'Prea multe comenzi într-un timp scurt. Reîncearcă în câteva minute.',
    en: 'Too many orders in a short time. Try again in a few minutes.',
    de: 'Zu viele Bestellungen in kurzer Zeit. Versuche es in ein paar Minuten erneut.',
    fr: 'Trop de commandes en peu de temps. Réessayez dans quelques minutes.',
    it: 'Troppi ordini in poco tempo. Riprova tra qualche minuto.',
    hu: 'Túl sok rendelés rövid idő alatt. Próbáld újra néhány perc múlva.',
    es: 'Demasiados pedidos en poco tiempo. Inténtalo de nuevo en unos minutos.',
  },
  err_table_unavailable: {
    ro: 'Masa tocmai a fost rezervată. Alege altă masă liberă.',
    en: 'That table was just booked. Please pick another free table.',
    de: 'Dieser Tisch wurde gerade reserviert. Bitte wähle einen anderen freien Tisch.',
    fr: 'Cette table vient d’être réservée. Choisissez une autre table libre.',
    it: 'Questo tavolo è appena stato prenotato. Scegline un altro libero.',
    hu: 'Ezt az asztalt épp most foglalták le. Válassz másik szabad asztalt.',
    es: 'Esa mesa se acaba de reservar. Elige otra mesa libre.',
  },
  err_rate_limit_reservation: {
    ro: 'Prea multe rezervări într-un interval scurt. Reîncearcă mai târziu.',
    en: 'Too many reservations in a short time. Try again later.',
    de: 'Zu viele Reservierungen in kurzer Zeit. Versuche es später erneut.',
    fr: 'Trop de réservations en peu de temps. Réessayez plus tard.',
    it: 'Troppe prenotazioni in poco tempo. Riprova più tardi.',
    hu: 'Túl sok foglalás rövid idő alatt. Próbáld újra később.',
    es: 'Demasiadas reservas en poco tiempo. Inténtalo más tarde.',
  },
  err_reservation_overlap: {
    ro: 'Intervalul ales se suprapune cu altă rezervare. Alege altă oră.',
    en: 'That time overlaps another reservation. Pick another slot.',
    de: 'Diese Zeit überschneidet sich mit einer anderen Reservierung. Wähle eine andere Uhrzeit.',
    fr: 'Ce créneau chevauche une autre réservation. Choisissez une autre heure.',
    it: 'Questo orario si sovrappone a un’altra prenotazione. Scegli un altro orario.',
    hu: 'Ez az időpont ütközik egy másik foglalással. Válassz másik időpontot.',
    es: 'Esa hora se solapa con otra reserva. Elige otra hora.',
  },
  err_reservation_day_closed: {
    ro: 'Restaurantul e închis în ziua aleasă. Alege altă zi.',
    en: 'The restaurant is closed on the selected day. Pick another day.',
    de: 'Das Restaurant ist am gewählten Tag geschlossen. Wähle einen anderen Tag.',
    fr: 'Le restaurant est fermé ce jour-là. Choisissez un autre jour.',
    it: 'Il ristorante è chiuso nel giorno scelto. Scegli un altro giorno.',
    hu: 'Az étterem a választott napon zárva van. Válassz másik napot.',
    es: 'El restaurante está cerrado ese día. Elige otro día.',
  },
  err_reservation_failed: {
    ro: 'Nu am putut salva rezervarea. Verifică datele și reîncearcă.',
    en: 'Could not save the reservation. Check the details and try again.',
    de: 'Die Reservierung konnte nicht gespeichert werden. Prüfe die Angaben und versuche es erneut.',
    fr: 'Impossible d’enregistrer la réservation. Vérifiez les informations et réessayez.',
    it: 'Impossibile salvare la prenotazione. Controlla i dati e riprova.',
    hu: 'Nem sikerült menteni a foglalást. Ellenőrizd az adatokat, és próbáld újra.',
    es: 'No se pudo guardar la reserva. Revisa los datos e inténtalo de nuevo.',
  },
  err_reservations_off: {
    ro: 'Rezervările nu sunt active pentru acest restaurant.',
    en: 'Reservations are not enabled for this restaurant.',
    de: 'Reservierungen sind für dieses Restaurant nicht aktiviert.',
    fr: 'Les réservations ne sont pas activées pour ce restaurant.',
    it: 'Le prenotazioni non sono attive per questo ristorante.',
    hu: 'Ennél az étteremnél nincs bekapcsolva a foglalás.',
    es: 'Las reservas no están activas en este restaurante.',
  },
  err_invalid_code: {
    ro: 'Cod de confirmare invalid.',
    en: 'Invalid confirmation code.',
    de: 'Ungültiger Bestätigungscode.',
    fr: 'Code de confirmation invalide.',
    it: 'Codice di conferma non valido.',
    hu: 'Érvénytelen visszaigazoló kód.',
    es: 'Código de confirmación no válido.',
  },
  err_module_disabled: {
    ro: 'Această funcție nu este activă la acest local.',
    en: 'This feature is not enabled at this venue.',
    de: 'Diese Funktion ist in diesem Lokal nicht aktiviert.',
    fr: 'Cette fonction n’est pas activée dans cet établissement.',
    it: 'Questa funzione non è attiva in questo locale.',
    hu: 'Ez a funkció ebben a vendéglátóhelyben nincs bekapcsolva.',
    es: 'Esta función no está activa en este local.',
  },
  err_payments_not_ready: {
    ro: 'Localul nu a terminat configurarea plăților online. Cere nota ospătarului.',
    en: 'The venue has not finished setting up online payments. Ask your waiter for the bill.',
    de: 'Das Lokal hat die Online-Zahlung noch nicht fertig eingerichtet. Bitte frag nach der Rechnung.',
    fr: 'L’établissement n’a pas fini de configurer le paiement en ligne. Demandez l’addition au serveur.',
    it: 'Il locale non ha completato la configurazione dei pagamenti online. Chiedi il conto al cameriere.',
    hu: 'A hely még nem állította be az online fizetést. Kérd el a számlát a pincértől.',
    es: 'El local no ha terminado de configurar los pagos en línea. Pide la cuenta al camarero.',
  },
  err_online_pay_off: {
    ro: 'Plata online nu este activată la acest local. Cere nota ospătarului.',
    en: 'Online payment is not enabled at this venue. Ask your waiter for the bill.',
    de: 'Online-Zahlung ist in diesem Lokal nicht aktiviert. Bitte frag nach der Rechnung.',
    fr: 'Le paiement en ligne n’est pas activé dans cet établissement. Demandez l’addition au serveur.',
    it: 'Il pagamento online non è attivo in questo locale. Chiedi il conto al cameriere.',
    hu: 'Ebben a vendéglátóhelyben nincs online fizetés. Kérd el a számlát a pincértől.',
    es: 'El pago en línea no está activo en este local. Pide la cuenta al camarero.',
  },
  err_split_off: {
    ro: 'Împărțirea notei nu este disponibilă la acest local.',
    en: 'Splitting the bill is not available at this venue.',
    de: 'Getrennt zahlen ist in diesem Lokal nicht möglich.',
    fr: 'Le partage de l’addition n’est pas disponible dans cet établissement.',
    it: 'La divisione del conto non è disponibile in questo locale.',
    hu: 'Ebben a vendéglátóhelyben nem lehet megosztani a számlát.',
    es: 'Dividir la cuenta no está disponible en este local.',
  },
  err_nothing_to_pay: {
    ro: 'Nu există comenzi de plătit — probabil nota a fost deja achitată.',
    en: 'There is nothing to pay — the bill has probably been settled already.',
    de: 'Es gibt nichts zu bezahlen – die Rechnung wurde wohl schon beglichen.',
    fr: 'Il n’y a rien à payer — l’addition a sans doute déjà été réglée.',
    it: 'Non c’è nulla da pagare: probabilmente il conto è già stato saldato.',
    hu: 'Nincs mit fizetni – a számlát valószínűleg már rendezték.',
    es: 'No hay nada que pagar: probablemente la cuenta ya está saldada.',
  },
  err_currency_not_supported: {
    ro: 'Plata online e disponibilă doar pentru meniuri în lei. Cere nota ospătarului.',
    en: 'Online payment is only available for menus priced in lei. Ask your waiter for the bill.',
    de: 'Online-Zahlung gibt es nur für Menüs in Lei. Bitte frag nach der Rechnung.',
    fr: 'Le paiement en ligne n’est disponible que pour les menus en lei. Demandez l’addition au serveur.',
    it: 'Il pagamento online è disponibile solo per menu in lei. Chiedi il conto al cameriere.',
    hu: 'Online fizetés csak lejben árazott menünél lehetséges. Kérd el a számlát a pincértől.',
    es: 'El pago en línea solo está disponible para menús en lei. Pide la cuenta al camarero.',
  },
  err_items_already_claimed: {
    ro: 'Cineva de la masă plătește deja o parte din aceste produse. Alege altele sau reîncearcă.',
    en: 'Someone at the table is already paying for some of these items. Choose others or try again.',
    de: 'Jemand am Tisch bezahlt bereits einige dieser Artikel. Wähle andere oder versuche es erneut.',
    fr: 'Quelqu’un à la table paie déjà une partie de ces articles. Choisissez-en d’autres ou réessayez.',
    it: 'Qualcuno al tavolo sta già pagando alcuni di questi prodotti. Scegline altri o riprova.',
    hu: 'Valaki az asztalnál már fizet néhány tételért. Válassz másikat, vagy próbáld újra.',
    es: 'Alguien en la mesa ya está pagando parte de estos productos. Elige otros o inténtalo de nuevo.',
  },
  err_bill_changed: {
    ro: 'Nota s-a schimbat între timp — redeschide împărțirea notei.',
    en: 'The bill has changed in the meantime — reopen bill splitting.',
    de: 'Die Rechnung hat sich inzwischen geändert – öffne das Aufteilen erneut.',
    fr: 'L’addition a changé entre-temps — rouvrez le partage.',
    it: 'Il conto è cambiato nel frattempo: riapri la divisione del conto.',
    hu: 'A számla időközben megváltozott – nyisd meg újra a megosztást.',
    es: 'La cuenta ha cambiado mientras tanto: vuelve a abrir la división.',
  },
  err_amount_mismatch: {
    ro: 'Suma nu mai corespunde cu nota. Reîncarcă și încearcă din nou.',
    en: 'The amount no longer matches the bill. Reload and try again.',
    de: 'Der Betrag stimmt nicht mehr mit der Rechnung überein. Lade neu und versuche es erneut.',
    fr: 'Le montant ne correspond plus à l’addition. Rechargez et réessayez.',
    it: 'L’importo non corrisponde più al conto. Ricarica e riprova.',
    hu: 'Az összeg már nem egyezik a számlával. Töltsd újra, és próbáld újra.',
    es: 'El importe ya no coincide con la cuenta. Recarga e inténtalo de nuevo.',
  },
  err_payment_failed: {
    ro: 'Plata nu a putut fi inițiată.',
    en: 'The payment could not be started.',
    de: 'Die Zahlung konnte nicht gestartet werden.',
    fr: 'Le paiement n’a pas pu être lancé.',
    it: 'Non è stato possibile avviare il pagamento.',
    hu: 'A fizetést nem sikerült elindítani.',
    es: 'No se pudo iniciar el pago.',
  },
  err_bill_load_failed: {
    ro: 'Nota nu a putut fi încărcată.',
    en: 'The bill could not be loaded.',
    de: 'Die Rechnung konnte nicht geladen werden.',
    fr: 'L’addition n’a pas pu être chargée.',
    it: 'Non è stato possibile caricare il conto.',
    hu: 'A számlát nem sikerült betölteni.',
    es: 'No se pudo cargar la cuenta.',
  },
  // ── Alergeni (Reg. UE 1169/2011, denumirile oficiale) ──
  allergen_gluten: {
    ro: 'Gluten',
    en: 'Gluten',
    de: 'Gluten',
    fr: 'Gluten',
    it: 'Glutine',
    hu: 'Glutén',
    es: 'Gluten',
  },
  allergen_crustacee: {
    ro: 'Crustacee',
    en: 'Crustaceans',
    de: 'Krebstiere',
    fr: 'Crustacés',
    it: 'Crostacei',
    hu: 'Rákfélék',
    es: 'Crustáceos',
  },
  allergen_oua: {
    ro: 'Ouă',
    en: 'Eggs',
    de: 'Eier',
    fr: 'Œufs',
    it: 'Uova',
    hu: 'Tojás',
    es: 'Huevos',
  },
  allergen_peste: {
    ro: 'Pește',
    en: 'Fish',
    de: 'Fisch',
    fr: 'Poisson',
    it: 'Pesce',
    hu: 'Hal',
    es: 'Pescado',
  },
  allergen_arahide: {
    ro: 'Arahide',
    en: 'Peanuts',
    de: 'Erdnüsse',
    fr: 'Arachides',
    it: 'Arachidi',
    hu: 'Földimogyoró',
    es: 'Cacahuetes',
  },
  allergen_soia: {
    ro: 'Soia',
    en: 'Soybeans',
    de: 'Soja',
    fr: 'Soja',
    it: 'Soia',
    hu: 'Szója',
    es: 'Soja',
  },
  allergen_lapte: {
    ro: 'Lapte',
    en: 'Milk',
    de: 'Milch',
    fr: 'Lait',
    it: 'Latte',
    hu: 'Tej',
    es: 'Leche',
  },
  allergen_nuci: {
    ro: 'Nuci',
    en: 'Nuts',
    de: 'Schalenfrüchte',
    fr: 'Fruits à coque',
    it: 'Frutta a guscio',
    hu: 'Diófélék',
    es: 'Frutos de cáscara',
  },
  allergen_telina: {
    ro: 'Țelină',
    en: 'Celery',
    de: 'Sellerie',
    fr: 'Céleri',
    it: 'Sedano',
    hu: 'Zeller',
    es: 'Apio',
  },
  allergen_mustar: {
    ro: 'Muștar',
    en: 'Mustard',
    de: 'Senf',
    fr: 'Moutarde',
    it: 'Senape',
    hu: 'Mustár',
    es: 'Mostaza',
  },
  allergen_susan: {
    ro: 'Susan',
    en: 'Sesame',
    de: 'Sesam',
    fr: 'Sésame',
    it: 'Sesamo',
    hu: 'Szezámmag',
    es: 'Sésamo',
  },
  allergen_sulfiti: {
    ro: 'Sulfiți',
    en: 'Sulphites',
    de: 'Sulfite',
    fr: 'Sulfites',
    it: 'Solfiti',
    hu: 'Szulfitok',
    es: 'Sulfitos',
  },
  allergen_lupin: {
    ro: 'Lupin',
    en: 'Lupin',
    de: 'Lupinen',
    fr: 'Lupin',
    it: 'Lupini',
    hu: 'Csillagfürt',
    es: 'Altramuces',
  },
  allergen_molusce: {
    ro: 'Moluște',
    en: 'Molluscs',
    de: 'Weichtiere',
    fr: 'Mollusques',
    it: 'Molluschi',
    hu: 'Puhatestűek',
    es: 'Moluscos',
  },
  // ── Etichete dietetice ──
  diet_signature: {
    ro: 'Signature',
    en: 'Signature',
    de: 'Signature',
    fr: 'Signature',
    it: 'Signature',
    hu: 'Signature',
    es: 'Signature',
  },
  diet_nou: {
    ro: 'Nou',
    en: 'New',
    de: 'Neu',
    fr: 'Nouveau',
    it: 'Novità',
    hu: 'Új',
    es: 'Nuevo',
  },
  diet_vegetarian: {
    ro: 'Vegetarian',
    en: 'Vegetarian',
    de: 'Vegetarisch',
    fr: 'Végétarien',
    it: 'Vegetariano',
    hu: 'Vegetáriánus',
    es: 'Vegetariano',
  },
  diet_vegan: {
    ro: 'Vegan',
    en: 'Vegan',
    de: 'Vegan',
    fr: 'Végan',
    it: 'Vegano',
    hu: 'Vegán',
    es: 'Vegano',
  },
  diet_fara_gluten: {
    ro: 'Fără gluten',
    en: 'Gluten-free',
    de: 'Glutenfrei',
    fr: 'Sans gluten',
    it: 'Senza glutine',
    hu: 'Gluténmentes',
    es: 'Sin gluten',
  },
  diet_fara_lactoza: {
    ro: 'Fără lactoză',
    en: 'Lactose-free',
    de: 'Laktosefrei',
    fr: 'Sans lactose',
    it: 'Senza lattosio',
    hu: 'Laktózmentes',
    es: 'Sin lactosa',
  },
  diet_picant: {
    ro: 'Picant',
    en: 'Spicy',
    de: 'Scharf',
    fr: 'Épicé',
    it: 'Piccante',
    hu: 'Csípős',
    es: 'Picante',
  },
  diet_raw: {
    ro: 'Raw',
    en: 'Raw',
    de: 'Roh',
    fr: 'Cru',
    it: 'Crudo',
    hu: 'Nyers',
    es: 'Crudo',
  },
  // ── Grupuri de opțiuni (oglinda modifierGroupHint) ──
  mod_choose_exact: {
    ro: 'Alege exact {n}',
    en: 'Choose exactly {n}',
    de: 'Wähle genau {n}',
    fr: 'Choisissez exactement {n}',
    it: 'Scegli esattamente {n}',
    hu: 'Válassz pontosan {n} db-ot',
    es: 'Elige exactamente {n}',
  },
  mod_choose_between: {
    ro: 'Alege între {min} și {max}',
    en: 'Choose between {min} and {max}',
    de: 'Wähle zwischen {min} und {max}',
    fr: 'Choisissez entre {min} et {max}',
    it: 'Scegli tra {min} e {max}',
    hu: 'Válassz {min}–{max} db-ot',
    es: 'Elige entre {min} y {max}',
  },
  mod_choose_at_least: {
    ro: 'Alege cel puțin {n}',
    en: 'Choose at least {n}',
    de: 'Wähle mindestens {n}',
    fr: 'Choisissez au moins {n}',
    it: 'Scegli almeno {n}',
    hu: 'Válassz legalább {n} db-ot',
    es: 'Elige al menos {n}',
  },
  mod_choose_max: {
    ro: 'Maxim {n}',
    en: 'Up to {n}',
    de: 'Höchstens {n}',
    fr: '{n} maximum',
    it: 'Massimo {n}',
    hu: 'Legfeljebb {n}',
    es: 'Máximo {n}',
  },
  // ── Stările meniului (MenuStates) + pagina QR ──
  menu_loading: {
    ro: 'Se încarcă meniul…',
    en: 'Loading the menu…',
    de: 'Menü wird geladen…',
    fr: 'Chargement du menu…',
    it: 'Caricamento del menu…',
    hu: 'A menü betöltése…',
    es: 'Cargando el menú…',
  },
  menu_preparing_title: {
    ro: 'Meniul se pregătește',
    en: 'The menu is being prepared',
    de: 'Das Menü wird vorbereitet',
    fr: 'Le menu est en préparation',
    it: 'Il menu è in preparazione',
    hu: 'A menü készül',
    es: 'El menú se está preparando',
  },
  menu_preparing_sub: {
    ro: 'Revino curând — preparatele vor apărea aici.',
    en: 'Come back soon — the dishes will appear here.',
    de: 'Schau bald wieder vorbei – die Gerichte erscheinen hier.',
    fr: 'Revenez bientôt — les plats apparaîtront ici.',
    it: 'Torna presto: i piatti appariranno qui.',
    hu: 'Nézz vissza hamarosan – az ételek itt jelennek meg.',
    es: 'Vuelve pronto: los platos aparecerán aquí.',
  },
  menu_load_error_title: {
    ro: 'Nu am putut încărca meniul',
    en: 'We couldn’t load the menu',
    de: 'Das Menü konnte nicht geladen werden',
    fr: 'Impossible de charger le menu',
    it: 'Non è stato possibile caricare il menu',
    hu: 'Nem sikerült betölteni a menüt',
    es: 'No pudimos cargar el menú',
  },
  menu_load_error_msg: {
    ro: 'Verifică conexiunea și încearcă din nou.',
    en: 'Check your connection and try again.',
    de: 'Prüfe deine Verbindung und versuche es erneut.',
    fr: 'Vérifiez votre connexion et réessayez.',
    it: 'Controlla la connessione e riprova.',
    hu: 'Ellenőrizd a kapcsolatot, és próbáld újra.',
    es: 'Revisa tu conexión e inténtalo de nuevo.',
  },
  retry: {
    ro: 'Reîncearcă',
    en: 'Try again',
    de: 'Erneut versuchen',
    fr: 'Réessayer',
    it: 'Riprova',
    hu: 'Újra',
    es: 'Reintentar',
  },
  qr_invalid_title: {
    ro: 'Acest QR nu mai este activ',
    en: 'This QR code is no longer active',
    de: 'Dieser QR-Code ist nicht mehr aktiv',
    fr: 'Ce QR code n’est plus actif',
    it: 'Questo codice QR non è più attivo',
    hu: 'Ez a QR-kód már nem aktív',
    es: 'Este código QR ya no está activo',
  },
  qr_invalid_msg: {
    ro: 'Te rugăm să ceri personalului un QR nou.',
    en: 'Please ask the staff for a new QR code.',
    de: 'Bitte frag das Personal nach einem neuen QR-Code.',
    fr: 'Merci de demander un nouveau QR code au personnel.',
    it: 'Chiedi al personale un nuovo codice QR.',
    hu: 'Kérj új QR-kódot a személyzettől.',
    es: 'Pide al personal un nuevo código QR.',
  },
  net_weak_title: {
    ro: 'Conexiune slabă',
    en: 'Weak connection',
    de: 'Schwache Verbindung',
    fr: 'Connexion faible',
    it: 'Connessione debole',
    hu: 'Gyenge kapcsolat',
    es: 'Conexión débil',
  },
  net_menu_msg: {
    ro: 'Nu s-a putut încărca meniul. Verifică internetul și încearcă din nou.',
    en: 'The menu could not be loaded. Check your internet and try again.',
    de: 'Das Menü konnte nicht geladen werden. Prüfe dein Internet und versuche es erneut.',
    fr: 'Le menu n’a pas pu être chargé. Vérifiez votre connexion et réessayez.',
    it: 'Non è stato possibile caricare il menu. Controlla internet e riprova.',
    hu: 'Nem sikerült betölteni a menüt. Ellenőrizd az internetet, és próbáld újra.',
    es: 'No se pudo cargar el menú. Revisa internet e inténtalo de nuevo.',
  },
  table_word: {
    ro: 'Masă',
    en: 'Table',
    de: 'Tisch',
    fr: 'Table',
    it: 'Tavolo',
    hu: 'Asztal',
    es: 'Mesa',
  },
  menu_unavailable: {
    ro: 'Momentan meniul nu este disponibil.',
    en: 'The menu is not available right now.',
    de: 'Das Menü ist gerade nicht verfügbar.',
    fr: 'Le menu n’est pas disponible pour le moment.',
    it: 'Il menu non è disponibile al momento.',
    hu: 'A menü jelenleg nem érhető el.',
    es: 'El menú no está disponible ahora mismo.',
  },
  try_other_word: {
    ro: 'Încearcă alt cuvânt.',
    en: 'Try another word.',
    de: 'Versuche ein anderes Wort.',
    fr: 'Essayez un autre mot.',
    it: 'Prova con un’altra parola.',
    hu: 'Próbálj másik szót.',
    es: 'Prueba con otra palabra.',
  },
  pairing_added: {
    ro: '{name} adăugat',
    en: '{name} added',
    de: '{name} hinzugefügt',
    fr: '{name} ajouté',
    it: '{name} aggiunto',
    hu: '{name} hozzáadva',
    es: '{name} añadido',
  },
  pairing_title: {
    ro: 'Merge perfect cu...',
    en: 'Goes perfectly with...',
    de: 'Passt perfekt zu...',
    fr: 'Se marie parfaitement avec...',
    it: 'Si abbina perfettamente con...',
    hu: 'Tökéletesen illik hozzá...',
    es: 'Combina perfectamente con...',
  },
  continue_menu: {
    ro: 'Continuă cu meniul',
    en: 'Back to the menu',
    de: 'Weiter zum Menü',
    fr: 'Continuer vers le menu',
    it: 'Continua con il menu',
    hu: 'Vissza a menühöz',
    es: 'Seguir con el menú',
  },
  add_named: {
    ro: 'Adaugă {name}',
    en: 'Add {name}',
    de: '{name} hinzufügen',
    fr: 'Ajouter {name}',
    it: 'Aggiungi {name}',
    hu: '{name} hozzáadása',
    es: 'Añadir {name}',
  },
  paid_online_done: {
    ro: 'Plătit online ✓',
    en: 'Paid online ✓',
    de: 'Online bezahlt ✓',
    fr: 'Payé en ligne ✓',
    it: 'Pagato online ✓',
    hu: 'Online kifizetve ✓',
    es: 'Pagado en línea ✓',
  },
  pay_online: {
    ro: 'Plătește online',
    en: 'Pay online',
    de: 'Online bezahlen',
    fr: 'Payer en ligne',
    it: 'Paga online',
    hu: 'Online fizetés',
    es: 'Pagar en línea',
  },
  bill_requested_done: {
    ro: 'Nota a fost cerută ✓',
    en: 'Bill requested ✓',
    de: 'Rechnung angefordert ✓',
    fr: 'Addition demandée ✓',
    it: 'Conto richiesto ✓',
    hu: 'Számla kérve ✓',
    es: 'Cuenta pedida ✓',
  },
  pay_table: {
    ro: 'Plătește masa',
    en: 'Pay for the table',
    de: 'Tisch bezahlen',
    fr: 'Régler la table',
    it: 'Paga il tavolo',
    hu: 'Asztal fizetése',
    es: 'Pagar la mesa',
  },
  // ── Cardurile de produs (menu/Product*) + CategoryTabs ──
  price_discounted_aria: {
    ro: 'Preț redus {price}, de la {base}',
    en: 'Discounted price {price}, down from {base}',
    de: 'Reduzierter Preis {price}, statt {base}',
    fr: 'Prix réduit {price}, au lieu de {base}',
    it: 'Prezzo scontato {price}, invece di {base}',
    hu: 'Akciós ár: {price}, eredetileg {base}',
    es: 'Precio rebajado {price}, antes {base}',
  },
  price_from: {
    ro: 'De la',
    en: 'From',
    de: 'Ab',
    fr: 'À partir de',
    it: 'Da',
    hu: 'Ettől:',
    es: 'Desde',
  },
  price_from_lc: {
    ro: 'de la',
    en: 'from',
    de: 'ab',
    fr: 'à partir de',
    it: 'da',
    hu: 'ettől',
    es: 'desde',
  },
  options_hint: {
    ro: 'opțiuni',
    en: 'options',
    de: 'Optionen',
    fr: 'options',
    it: 'opzioni',
    hu: 'opciók',
    es: 'opciones',
  },
  sold_out: {
    ro: 'Epuizat',
    en: 'Sold out',
    de: 'Ausverkauft',
    fr: 'Épuisé',
    it: 'Esaurito',
    hu: 'Elfogyott',
    es: 'Agotado',
  },
  products_count: {
    ro: 'produse',
    en: 'items',
    de: 'Artikel',
    fr: 'articles',
    it: 'prodotti',
    hu: 'tétel',
    es: 'productos',
  },
  // ── Flipbook / harta sălii / antet ──
  flip_empty_title: {
    ro: 'Meniul nu are încă pagini încărcate',
    en: 'The menu has no pages yet',
    de: 'Das Menü hat noch keine Seiten',
    fr: 'Le menu n’a pas encore de pages',
    it: 'Il menu non ha ancora pagine',
    hu: 'A menünek még nincsenek oldalai',
    es: 'El menú aún no tiene páginas',
  },
  flip_empty_sub: {
    ro: 'Paginile meniului vor apărea aici de îndată ce restaurantul le încarcă.',
    en: 'The menu pages will appear here as soon as the restaurant uploads them.',
    de: 'Die Menüseiten erscheinen hier, sobald das Restaurant sie hochlädt.',
    fr: 'Les pages du menu apparaîtront ici dès que le restaurant les aura ajoutées.',
    it: 'Le pagine del menu appariranno qui appena il ristorante le carica.',
    hu: 'A menü oldalai itt jelennek meg, amint az étterem feltölti őket.',
    es: 'Las páginas del menú aparecerán aquí en cuanto el restaurante las suba.',
  },
  flip_prev: {
    ro: 'Pagina anterioară',
    en: 'Previous page',
    de: 'Vorherige Seite',
    fr: 'Page précédente',
    it: 'Pagina precedente',
    hu: 'Előző oldal',
    es: 'Página anterior',
  },
  flip_next: {
    ro: 'Pagina următoare',
    en: 'Next page',
    de: 'Nächste Seite',
    fr: 'Page suivante',
    it: 'Pagina successiva',
    hu: 'Következő oldal',
    es: 'Página siguiente',
  },
  floor_map_aria: {
    ro: 'Harta sălii',
    en: 'Floor plan',
    de: 'Raumplan',
    fr: 'Plan de salle',
    it: 'Pianta della sala',
    hu: 'Teremtérkép',
    es: 'Plano de la sala',
  },
  floor_table_free: {
    ro: 'Masa {name} — liberă',
    en: 'Table {name} — free',
    de: 'Tisch {name} – frei',
    fr: 'Table {name} — libre',
    it: 'Tavolo {name} — libero',
    hu: '{name}. asztal – szabad',
    es: 'Mesa {name} — libre',
  },
  floor_table_busy: {
    ro: 'Masa {name} — ocupată',
    en: 'Table {name} — taken',
    de: 'Tisch {name} – belegt',
    fr: 'Table {name} — occupée',
    it: 'Tavolo {name} — occupato',
    hu: '{name}. asztal – foglalt',
    es: 'Mesa {name} — ocupada',
  },
  closed_badge: {
    ro: 'Închis',
    en: 'Closed',
    de: 'Geschlossen',
    fr: 'Fermé',
    it: 'Chiuso',
    hu: 'Zárva',
    es: 'Cerrado',
  },
  cover_alt: {
    ro: 'Imagine de copertă — {name}',
    en: 'Cover image — {name}',
    de: 'Titelbild – {name}',
    fr: 'Image de couverture — {name}',
    it: 'Immagine di copertina — {name}',
    hu: 'Borítókép – {name}',
    es: 'Imagen de portada — {name}',
  },
  flip_aria: {
    ro: 'Paginile meniului, {n} pagini. Glisează orizontal pentru a răsfoi.',
    en: 'Menu pages, {n} pages. Swipe horizontally to browse.',
    de: 'Menüseiten, {n} Seiten. Horizontal wischen zum Blättern.',
    fr: 'Pages du menu, {n} pages. Balayez horizontalement pour feuilleter.',
    it: 'Pagine del menu, {n} pagine. Scorri in orizzontale per sfogliare.',
    hu: 'A menü oldalai, {n} oldal. Lapozáshoz húzd vízszintesen.',
    es: 'Páginas del menú, {n} páginas. Desliza en horizontal para hojearlo.',
  },
  flip_page_alt: {
    ro: 'Pagina {n} din meniu',
    en: 'Menu page {n}',
    de: 'Menüseite {n}',
    fr: 'Page {n} du menu',
    it: 'Pagina {n} del menu',
    hu: 'A menü {n}. oldala',
    es: 'Página {n} del menú',
  },
  flip_page_badge: {
    ro: 'pagina {n}/{total}',
    en: 'page {n}/{total}',
    de: 'Seite {n}/{total}',
    fr: 'page {n}/{total}',
    it: 'pagina {n}/{total}',
    hu: '{n}/{total}. oldal',
    es: 'página {n}/{total}',
  },
  floor_table: {
    ro: 'Masa {name}',
    en: 'Table {name}',
    de: 'Tisch {name}',
    fr: 'Table {name}',
    it: 'Tavolo {name}',
    hu: '{name}. asztal',
    es: 'Mesa {name}',
  },
  lang_switch_aria: {
    ro: 'Alege limba meniului',
    en: 'Choose the menu language',
    de: 'Menüsprache wählen',
    fr: 'Choisir la langue du menu',
    it: 'Scegli la lingua del menu',
    hu: 'Válaszd ki a menü nyelvét',
    es: 'Elige el idioma del menú',
  },
  open_now_short: {
    ro: 'Deschis acum',
    en: 'Open now',
    de: 'Jetzt geöffnet',
    fr: 'Ouvert',
    it: 'Aperto ora',
    hu: 'Most nyitva',
    es: 'Abierto ahora',
  },
  status_aria: {
    ro: 'Status: {label}',
    en: 'Status: {label}',
    de: 'Status: {label}',
    fr: 'Statut : {label}',
    it: 'Stato: {label}',
    hu: 'Állapot: {label}',
    es: 'Estado: {label}',
  },
  categories_aria: {
    ro: 'Categorii meniu',
    en: 'Menu categories',
    de: 'Menükategorien',
    fr: 'Catégories du menu',
    it: 'Categorie del menu',
    hu: 'Menükategóriák',
    es: 'Categorías del menú',
  },
  brand_agency: {
    ro: 'Meniu digital de {name}',
    en: 'Digital menu by {name}',
    de: 'Digitales Menü von {name}',
    fr: 'Menu digital par {name}',
    it: 'Menu digitale di {name}',
    hu: 'Digitális menü: {name}',
    es: 'Menú digital de {name}',
  },
  brand_menuvia: {
    ro: 'Meniu digital creat cu Menuvia',
    en: 'Digital menu made with Menuvia',
    de: 'Digitales Menü erstellt mit Menuvia',
    fr: 'Menu digital créé avec Menuvia',
    it: 'Menu digitale creato con Menuvia',
    hu: 'Digitális menü – Menuvia',
    es: 'Menú digital creado con Menuvia',
  },
  view_details_named: {
    ro: 'Vezi detalii {name}',
    en: 'View details: {name}',
    de: 'Details: {name}',
    fr: 'Voir les détails : {name}',
    it: 'Vedi dettagli: {name}',
    hu: 'Részletek: {name}',
    es: 'Ver detalles: {name}',
  },
  // ── Fișa produsului (ProductSheet) ──
  ps_special: {
    ro: 'Specialitate',
    en: 'Daily special',
    de: 'Tagesempfehlung',
    fr: 'Spécialité',
    it: 'Specialità',
    hu: 'Napi ajánlat',
    es: 'Especialidad',
  },
  allergens_title: {
    ro: 'Alergeni',
    en: 'Allergens',
    de: 'Allergene',
    fr: 'Allergènes',
    it: 'Allergeni',
    hu: 'Allergének',
    es: 'Alérgenos',
  },
  illustrative_image: {
    ro: 'Imagine ilustrativă',
    en: 'Illustrative image',
    de: 'Abbildung ähnlich',
    fr: 'Photo non contractuelle',
    it: 'Immagine illustrativa',
    hu: 'Illusztráció',
    es: 'Imagen ilustrativa',
  },
  hh_auto_note: {
    ro: 'Reducerea Happy Hour se aplică automat la trimiterea comenzii.',
    en: 'The Happy Hour discount is applied automatically when you send your order.',
    de: 'Der Happy-Hour-Rabatt wird beim Absenden der Bestellung automatisch abgezogen.',
    fr: 'La remise Happy Hour s’applique automatiquement à l’envoi de la commande.',
    it: 'Lo sconto Happy Hour si applica automaticamente all’invio dell’ordine.',
    hu: 'A Happy Hour kedvezmény a rendelés elküldésekor automatikusan érvényesül.',
    es: 'El descuento Happy Hour se aplica automáticamente al enviar el pedido.',
  },
  nut_calories: {
    ro: 'Calorii',
    en: 'Calories',
    de: 'Kalorien',
    fr: 'Calories',
    it: 'Calorie',
    hu: 'Kalória',
    es: 'Calorías',
  },
  nut_protein: {
    ro: 'Proteine',
    en: 'Protein',
    de: 'Eiweiß',
    fr: 'Protéines',
    it: 'Proteine',
    hu: 'Fehérje',
    es: 'Proteínas',
  },
  nut_carbs: {
    ro: 'Carbo',
    en: 'Carbs',
    de: 'Kohlenhydrate',
    fr: 'Glucides',
    it: 'Carboidrati',
    hu: 'Szénhidrát',
    es: 'Carbohidratos',
  },
  nut_fat: {
    ro: 'Grăsimi',
    en: 'Fat',
    de: 'Fett',
    fr: 'Lipides',
    it: 'Grassi',
    hu: 'Zsír',
    es: 'Grasas',
  },
  nut_estimate: {
    ro: 'Valori estimative, per porție',
    en: 'Estimated values, per serving',
    de: 'Geschätzte Werte pro Portion',
    fr: 'Valeurs estimées, par portion',
    it: 'Valori stimati, per porzione',
    hu: 'Becsült értékek adagonként',
    es: 'Valores estimados, por ración',
  },
  mod_selected: {
    ro: 'ales',
    en: 'selected',
    de: 'gewählt',
    fr: 'choisi',
    it: 'scelto',
    hu: 'kiválasztva',
    es: 'elegido',
  },
  mod_required: {
    ro: 'Obligatoriu',
    en: 'Required',
    de: 'Pflicht',
    fr: 'Obligatoire',
    it: 'Obbligatorio',
    hu: 'Kötelező',
    es: 'Obligatorio',
  },
  mod_optional: {
    ro: 'Opțional',
    en: 'Optional',
    de: 'Optional',
    fr: 'Facultatif',
    it: 'Facoltativo',
    hu: 'Választható',
    es: 'Opcional',
  },
  add_extras: {
    ro: 'Adaugă extra',
    en: 'Add extras',
    de: 'Extras hinzufügen',
    fr: 'Ajouter des suppléments',
    it: 'Aggiungi extra',
    hu: 'Extrák hozzáadása',
    es: 'Añadir extras',
  },
  quantity: {
    ro: 'Cantitate',
    en: 'Quantity',
    de: 'Menge',
    fr: 'Quantité',
    it: 'Quantità',
    hu: 'Mennyiség',
    es: 'Cantidad',
  },
  qty_dec: {
    ro: 'Scade cantitatea',
    en: 'Decrease quantity',
    de: 'Menge verringern',
    fr: 'Diminuer la quantité',
    it: 'Diminuisci la quantità',
    hu: 'Mennyiség csökkentése',
    es: 'Reducir la cantidad',
  },
  qty_inc: {
    ro: 'Crește cantitatea',
    en: 'Increase quantity',
    de: 'Menge erhöhen',
    fr: 'Augmenter la quantité',
    it: 'Aumenta la quantità',
    hu: 'Mennyiség növelése',
    es: 'Aumentar la cantidad',
  },
  special_requests_opt: {
    ro: 'Mențiuni speciale (opțional)',
    en: 'Special requests (optional)',
    de: 'Besondere Wünsche (optional)',
    fr: 'Demandes particulières (facultatif)',
    it: 'Richieste particolari (facoltativo)',
    hu: 'Különleges kérés (nem kötelező)',
    es: 'Peticiones especiales (opcional)',
  },
  more_info: {
    ro: 'Mai multe info',
    en: 'More info',
    de: 'Mehr Infos',
    fr: 'Plus d’infos',
    it: 'Più info',
    hu: 'További infó',
    es: 'Más información',
  },
  diet_tags_title: {
    ro: 'Etichete dietetice',
    en: 'Dietary labels',
    de: 'Ernährungshinweise',
    fr: 'Mentions alimentaires',
    it: 'Indicazioni dietetiche',
    hu: 'Étrendi jelölések',
    es: 'Etiquetas dietéticas',
  },
  add_to_cart: {
    ro: 'Adaugă în coș',
    en: 'Add to cart',
    de: 'In den Warenkorb',
    fr: 'Ajouter au panier',
    it: 'Aggiungi al carrello',
    hu: 'Kosárba',
    es: 'Añadir al carrito',
  },
  select_required: {
    ro: 'Selectează opțiunile obligatorii',
    en: 'Select the required options',
    de: 'Pflichtoptionen auswählen',
    fr: 'Choisissez les options obligatoires',
    it: 'Seleziona le opzioni obbligatorie',
    hu: 'Válaszd ki a kötelező opciókat',
    es: 'Elige las opciones obligatorias',
  },
  // ── Coșul la masă (QrCartSheet) ──
  qc_upsell: {
    ro: 'Ai vrea ceva în plus înainte să trimiți?',
    en: 'Would you like anything else before sending?',
    de: 'Darf es noch etwas sein, bevor du bestellst?',
    fr: 'Envie d’autre chose avant d’envoyer ?',
    it: 'Vuoi aggiungere qualcos’altro prima di inviare?',
    hu: 'Kérsz még valamit, mielőtt elküldöd?',
    es: '¿Quieres algo más antes de enviar?',
  },
  qc_title: {
    ro: 'Masa ta',
    en: 'Your table',
    de: 'Dein Tisch',
    fr: 'Votre table',
    it: 'Il tuo tavolo',
    hu: 'Az asztalod',
    es: 'Tu mesa',
  },
  qc_subtitle: {
    ro: 'Adaugă oricând, plătești când vrei.',
    en: 'Add anytime, pay whenever you like.',
    de: 'Bestell jederzeit nach, zahl wann du willst.',
    fr: 'Ajoutez à tout moment, payez quand vous voulez.',
    it: 'Aggiungi quando vuoi, paghi quando preferisci.',
    hu: 'Rendelj bármikor, fizess, amikor akarsz.',
    es: 'Añade cuando quieras y paga cuando prefieras.',
  },
  qc_at_kitchen: {
    ro: 'La bucătărie',
    en: 'In the kitchen',
    de: 'In der Küche',
    fr: 'En cuisine',
    it: 'In cucina',
    hu: 'A konyhán',
    es: 'En cocina',
  },
  qc_sent_to_kitchen: {
    ro: 'Trimisă la bucătărie',
    en: 'Sent to the kitchen',
    de: 'An die Küche gesendet',
    fr: 'Envoyée en cuisine',
    it: 'Inviato in cucina',
    hu: 'Elküldve a konyhára',
    es: 'Enviado a cocina',
  },
  qc_in_cart: {
    ro: 'În coș · de trimis',
    en: 'In cart · to send',
    de: 'Im Warenkorb · zu senden',
    fr: 'Dans le panier · à envoyer',
    it: 'Nel carrello · da inviare',
    hu: 'Kosárban · elküldendő',
    es: 'En el carrito · por enviar',
  },
  qc_empty_more: {
    ro: 'Coșul e gol. Atinge un produs din meniu ca să mai comanzi.',
    en: 'Your cart is empty. Tap an item on the menu to order more.',
    de: 'Dein Warenkorb ist leer. Tippe auf ein Gericht, um nachzubestellen.',
    fr: 'Votre panier est vide. Touchez un article du menu pour commander à nouveau.',
    it: 'Il carrello è vuoto. Tocca un prodotto del menu per ordinare ancora.',
    hu: 'A kosár üres. Koppints egy tételre a menüben, ha még rendelnél.',
    es: 'Tu carrito está vacío. Toca un producto del menú para pedir más.',
  },
  qc_empty: {
    ro: 'Coșul e gol. Atinge un produs din meniu ca să-l adaugi aici.',
    en: 'Your cart is empty. Tap an item on the menu to add it here.',
    de: 'Dein Warenkorb ist leer. Tippe auf ein Gericht im Menü, um es hinzuzufügen.',
    fr: 'Votre panier est vide. Touchez un article du menu pour l’ajouter ici.',
    it: 'Il carrello è vuoto. Tocca un prodotto del menu per aggiungerlo qui.',
    hu: 'A kosár üres. Koppints egy tételre a menüben, hogy ide kerüljön.',
    es: 'Tu carrito está vacío. Toca un producto del menú para añadirlo aquí.',
  },
  remove_named: {
    ro: 'Elimină {name}',
    en: 'Remove {name}',
    de: '{name} entfernen',
    fr: 'Retirer {name}',
    it: 'Rimuovi {name}',
    hu: '{name} eltávolítása',
    es: 'Quitar {name}',
  },
  qc_kitchen_note: {
    ro: 'Notă pentru bucătărie',
    en: 'Note for the kitchen',
    de: 'Hinweis für die Küche',
    fr: 'Note pour la cuisine',
    it: 'Nota per la cucina',
    hu: 'Megjegyzés a konyhának',
    es: 'Nota para la cocina',
  },
  qc_kitchen_note_ph: {
    ro: 'Fără ceapă, vă rog...',
    en: 'No onions, please...',
    de: 'Ohne Zwiebeln, bitte...',
    fr: 'Sans oignons, s’il vous plaît...',
    it: 'Senza cipolla, per favore...',
    hu: 'Hagyma nélkül, kérem...',
    es: 'Sin cebolla, por favor...',
  },
  qc_suggested: {
    ro: 'Recomandate alături',
    en: 'Goes well with',
    de: 'Passt gut dazu',
    fr: 'À accompagner de',
    it: 'Consigliati in abbinamento',
    hu: 'Ajánljuk mellé',
    es: 'Para acompañar',
  },
  qc_total_note: {
    ro: 'Totalul final este confirmat de restaurant.',
    en: 'The final total is confirmed by the restaurant.',
    de: 'Die Endsumme bestätigt das Restaurant.',
    fr: 'Le total final est confirmé par le restaurant.',
    it: 'Il totale finale è confermato dal ristorante.',
    hu: 'A végösszeget az étterem erősíti meg.',
    es: 'El total final lo confirma el restaurante.',
  },
  qc_send_rest: {
    ro: 'Trimite și restul',
    en: 'Send the rest too',
    de: 'Rest auch senden',
    fr: 'Envoyer le reste',
    it: 'Invia anche il resto',
    hu: 'A többit is küldd',
    es: 'Enviar también el resto',
  },
  qc_send_order: {
    ro: 'Trimite comanda',
    en: 'Send order',
    de: 'Bestellung senden',
    fr: 'Envoyer la commande',
    it: 'Invia l’ordine',
    hu: 'Rendelés elküldése',
    es: 'Enviar pedido',
  },
  qc_split: {
    ro: 'Împarte nota — plătește partea ta',
    en: 'Split the bill — pay your share',
    de: 'Rechnung teilen – zahl deinen Anteil',
    fr: 'Partager l’addition — payez votre part',
    it: 'Dividi il conto — paga la tua parte',
    hu: 'Számla megosztása – fizesd a részed',
    es: 'Dividir la cuenta — paga tu parte',
  },
  err_feature_disabled: {
    ro: 'Această funcție nu este disponibilă la acest local.',
    en: 'This feature is not available at this venue.',
    de: 'Diese Funktion ist in diesem Lokal nicht verfügbar.',
    fr: 'Cette fonction n’est pas disponible dans cet établissement.',
    it: 'Questa funzione non è disponibile in questo locale.',
    hu: 'Ez a funkció ebben a vendéglátóhelyben nem érhető el.',
    es: 'Esta función no está disponible en este local.',
  },
  // ── Plata online a mesei (PayTableSheet) ──
  pay_your_share: {
    ro: 'Plătește partea ta',
    en: 'Pay your share',
    de: 'Deinen Anteil bezahlen',
    fr: 'Payer votre part',
    it: 'Paga la tua parte',
    hu: 'Fizesd a részed',
    es: 'Paga tu parte',
  },
  pt_declined: {
    ro: 'Plata a fost refuzată. Încearcă alt card.',
    en: 'The payment was declined. Try another card.',
    de: 'Die Zahlung wurde abgelehnt. Versuche eine andere Karte.',
    fr: 'Le paiement a été refusé. Essayez une autre carte.',
    it: 'Il pagamento è stato rifiutato. Prova un’altra carta.',
    hu: 'A fizetést elutasították. Próbálj másik kártyát.',
    es: 'El pago ha sido rechazado. Prueba otra tarjeta.',
  },
  pt_processing: {
    ro: 'Plata se procesează — confirmarea apare în scurt timp. Nu mai încerca o dată.',
    en: 'Your payment is processing — confirmation will appear shortly. Please don’t try again.',
    de: 'Deine Zahlung wird bearbeitet – die Bestätigung erscheint gleich. Bitte nicht erneut versuchen.',
    fr: 'Votre paiement est en cours — la confirmation arrive sous peu. Ne réessayez pas.',
    it: 'Il pagamento è in elaborazione: la conferma arriverà a breve. Non riprovare.',
    hu: 'A fizetés feldolgozás alatt – a visszaigazolás hamarosan megjelenik. Ne próbáld újra.',
    es: 'Tu pago se está procesando: la confirmación llegará en breve. No lo intentes de nuevo.',
  },
  pt_confirm_failed: {
    ro: 'Eroare la confirmare. Reîncearcă.',
    en: 'Confirmation failed. Please try again.',
    de: 'Bestätigung fehlgeschlagen. Bitte versuche es erneut.',
    fr: 'Échec de la confirmation. Veuillez réessayer.',
    it: 'Conferma non riuscita. Riprova.',
    hu: 'A megerősítés nem sikerült. Próbáld újra.',
    es: 'Error al confirmar. Inténtalo de nuevo.',
  },
  pt_preparing: {
    ro: 'Se pregătește plata…',
    en: 'Preparing the payment…',
    de: 'Zahlung wird vorbereitet…',
    fr: 'Préparation du paiement…',
    it: 'Preparazione del pagamento…',
    hu: 'A fizetés előkészítése…',
    es: 'Preparando el pago…',
  },
  pt_done: {
    ro: 'Plata a fost efectuată.',
    en: 'Payment completed.',
    de: 'Zahlung abgeschlossen.',
    fr: 'Paiement effectué.',
    it: 'Pagamento effettuato.',
    hu: 'A fizetés megtörtént.',
    es: 'Pago realizado.',
  },
  pt_done_receipt: {
    ro: 'Bonul fiscal se emite la casa restaurantului. Mulțumim!',
    en: 'The fiscal receipt is issued at the restaurant’s till. Thank you!',
    de: 'Der Kassenbon wird an der Kasse des Restaurants ausgestellt. Danke!',
    fr: 'Le ticket de caisse est émis à la caisse du restaurant. Merci !',
    it: 'Lo scontrino fiscale viene emesso alla cassa del ristorante. Grazie!',
    hu: 'A nyugtát az étterem kasszája állítja ki. Köszönjük!',
    es: 'El ticket fiscal se emite en la caja del restaurante. ¡Gracias!',
  },
  pt_secure: {
    ro: 'Plată securizată prin Stripe. Banii ajung direct la restaurant.',
    en: 'Secure payment via Stripe. The money goes straight to the restaurant.',
    de: 'Sichere Zahlung über Stripe. Das Geld geht direkt an das Restaurant.',
    fr: 'Paiement sécurisé par Stripe. L’argent va directement au restaurant.',
    it: 'Pagamento sicuro tramite Stripe. Il denaro va direttamente al ristorante.',
    hu: 'Biztonságos fizetés a Stripe-on keresztül. A pénz közvetlenül az étteremhez kerül.',
    es: 'Pago seguro con Stripe. El dinero va directamente al restaurante.',
  },
  pt_processing_short: {
    ro: 'Se procesează…',
    en: 'Processing…',
    de: 'Wird bearbeitet…',
    fr: 'Traitement…',
    it: 'Elaborazione…',
    hu: 'Feldolgozás…',
    es: 'Procesando…',
  },
  pt_pay_amount: {
    ro: 'Plătește {amount}',
    en: 'Pay {amount}',
    de: '{amount} bezahlen',
    fr: 'Payer {amount}',
    it: 'Paga {amount}',
    hu: '{amount} fizetése',
    es: 'Pagar {amount}',
  },
  pt_pay: {
    ro: 'Plătește',
    en: 'Pay',
    de: 'Bezahlen',
    fr: 'Payer',
    it: 'Paga',
    hu: 'Fizetés',
    es: 'Pagar',
  },
  pt_pay_waiter: {
    ro: 'Renunț — plătesc la ospătar',
    en: 'Cancel — I’ll pay the waiter',
    de: 'Abbrechen – ich zahle beim Kellner',
    fr: 'Annuler — je paierai au serveur',
    it: 'Annulla — pago al cameriere',
    hu: 'Mégse – a pincérnél fizetek',
    es: 'Cancelar — pagaré al camarero',
  },
  // ── Împărțirea notei (SplitBillSheet) ──
  sb_title: {
    ro: 'Împarte nota',
    en: 'Split the bill',
    de: 'Rechnung teilen',
    fr: 'Partager l’addition',
    it: 'Dividi il conto',
    hu: 'Számla megosztása',
    es: 'Dividir la cuenta',
  },
  sb_subtitle: {
    ro: 'Alege produsele tale — plătești doar partea ta, cu cardul.',
    en: 'Pick your items — you pay only your share, by card.',
    de: 'Wähle deine Artikel – du zahlst nur deinen Anteil, per Karte.',
    fr: 'Choisissez vos articles — vous ne payez que votre part, par carte.',
    it: 'Scegli i tuoi prodotti: paghi solo la tua parte, con carta.',
    hu: 'Válaszd ki a tételeidet – csak a részedet fizeted, kártyával.',
    es: 'Elige tus productos: pagas solo tu parte, con tarjeta.',
  },
  sb_loading: {
    ro: 'Se încarcă nota mesei…',
    en: 'Loading the table bill…',
    de: 'Rechnung wird geladen…',
    fr: 'Chargement de l’addition…',
    it: 'Caricamento del conto…',
    hu: 'Az asztal számlájának betöltése…',
    es: 'Cargando la cuenta de la mesa…',
  },
  sb_partial_order: {
    ro: 'Această comandă se încheie la ospătar (are o plată parțială în desfășurare).',
    en: 'This order is settled with the waiter (a partial payment is in progress).',
    de: 'Diese Bestellung wird beim Kellner abgerechnet (eine Teilzahlung läuft).',
    fr: 'Cette commande se règle auprès du serveur (un paiement partiel est en cours).',
    it: 'Questo ordine si chiude con il cameriere (è in corso un pagamento parziale).',
    hu: 'Ezt a rendelést a pincérnél kell rendezni (részfizetés van folyamatban).',
    es: 'Este pedido se cierra con el camarero (hay un pago parcial en curso).',
  },
  sb_claimed_qty: {
    ro: '{n} deja în plată',
    en: '{n} already being paid',
    de: '{n} werden schon bezahlt',
    fr: '{n} déjà en paiement',
    it: '{n} già in pagamento',
    hu: '{n} már fizetés alatt',
    es: '{n} ya en pago',
  },
  sb_qty_dec_named: {
    ro: 'Scade cantitatea pentru {name}',
    en: 'Decrease quantity of {name}',
    de: 'Menge von {name} verringern',
    fr: 'Diminuer la quantité de {name}',
    it: 'Diminuisci la quantità di {name}',
    hu: '{name} mennyiségének csökkentése',
    es: 'Reducir la cantidad de {name}',
  },
  sb_qty_inc_named: {
    ro: 'Crește cantitatea pentru {name}',
    en: 'Increase quantity of {name}',
    de: 'Menge von {name} erhöhen',
    fr: 'Augmenter la quantité de {name}',
    it: 'Aumenta la quantità di {name}',
    hu: '{name} mennyiségének növelése',
    es: 'Aumentar la cantidad de {name}',
  },
  sb_in_payment: {
    ro: 'în plată ✓',
    en: 'being paid ✓',
    de: 'wird bezahlt ✓',
    fr: 'en paiement ✓',
    it: 'in pagamento ✓',
    hu: 'fizetés alatt ✓',
    es: 'en pago ✓',
  },
  sb_continue: {
    ro: 'Continuă la plată · ~{amount}',
    en: 'Continue to payment · ~{amount}',
    de: 'Weiter zur Zahlung · ~{amount}',
    fr: 'Continuer vers le paiement · ~{amount}',
    it: 'Continua al pagamento · ~{amount}',
    hu: 'Tovább a fizetéshez · ~{amount}',
    es: 'Continuar al pago · ~{amount}',
  },
  sb_pick: {
    ro: 'Alege produsele tale',
    en: 'Pick your items',
    de: 'Wähle deine Artikel',
    fr: 'Choisissez vos articles',
    it: 'Scegli i tuoi prodotti',
    hu: 'Válaszd ki a tételeidet',
    es: 'Elige tus productos',
  },
  sb_estimate: {
    ro: 'Estimare: {amount} — suma finală o confirmă serverul înainte de plată.',
    en: 'Estimate: {amount} — the final amount is confirmed before payment.',
    de: 'Schätzung: {amount} – der Endbetrag wird vor der Zahlung bestätigt.',
    fr: 'Estimation : {amount} — le montant final est confirmé avant le paiement.',
    it: 'Stima: {amount} — l’importo finale viene confermato prima del pagamento.',
    hu: 'Becslés: {amount} – a végösszeget fizetés előtt megerősítjük.',
    es: 'Estimación: {amount} — el importe final se confirma antes del pago.',
  },
  // ── Comanda pentru ridicare (PickupCheckoutSheet) ──
  pk_title: {
    ro: 'Detalii ridicare',
    en: 'Pickup details',
    de: 'Abholdetails',
    fr: 'Détails du retrait',
    it: 'Dettagli del ritiro',
    hu: 'Átvételi adatok',
    es: 'Datos de recogida',
  },
  pk_pay_note: {
    ro: 'Plata se face cash la ridicare.',
    en: 'You pay in cash at pickup.',
    de: 'Du bezahlst bar bei der Abholung.',
    fr: 'Le paiement se fait en espèces au retrait.',
    it: 'Si paga in contanti al ritiro.',
    hu: 'Átvételkor készpénzzel fizetsz.',
    es: 'Pagas en efectivo al recoger.',
  },
  pk_name: {
    ro: 'Nume',
    en: 'Name',
    de: 'Name',
    fr: 'Nom',
    it: 'Nome',
    hu: 'Név',
    es: 'Nombre',
  },
  pk_name_ph: {
    ro: 'Ion Popescu',
    en: 'John Smith',
    de: 'Max Mustermann',
    fr: 'Jean Dupont',
    it: 'Mario Rossi',
    hu: 'Kovács János',
    es: 'Juan Pérez',
  },
  pk_phone_hint: {
    ro: 'Obligatoriu — pentru a putea fi sunat dacă întârzii',
    en: 'Required — so the restaurant can call you if you’re late',
    de: 'Pflichtfeld – damit das Restaurant dich anrufen kann, falls du dich verspätest',
    fr: 'Obligatoire — pour que le restaurant puisse vous appeler en cas de retard',
    it: 'Obbligatorio — per poterti chiamare se fai tardi',
    hu: 'Kötelező – hogy felhívhassanak, ha késel',
    es: 'Obligatorio — para poder llamarte si te retrasas',
  },
  pk_come_at: {
    ro: 'Vino la',
    en: 'Pick up at',
    de: 'Abholung um',
    fr: 'Retrait à',
    it: 'Ritiro alle',
    hu: 'Átvétel',
    es: 'Recogida a las',
  },
  pk_closed_now: {
    ro: 'Restaurantul este închis acum. Revino în programul de funcționare.',
    en: 'The restaurant is closed now. Come back during opening hours.',
    de: 'Das Restaurant ist gerade geschlossen. Komm während der Öffnungszeiten wieder.',
    fr: 'Le restaurant est fermé pour le moment. Revenez pendant les heures d’ouverture.',
    it: 'Il ristorante ora è chiuso. Torna durante l’orario di apertura.',
    hu: 'Az étterem most zárva van. Gyere vissza nyitvatartási időben.',
    es: 'El restaurante está cerrado ahora. Vuelve en horario de apertura.',
  },
  pk_closed_banner: {
    ro: 'Restaurantul este închis acum. Vino mâine în orele de program.',
    en: 'The restaurant is closed now. Come back tomorrow during opening hours.',
    de: 'Das Restaurant ist gerade geschlossen. Komm morgen während der Öffnungszeiten.',
    fr: 'Le restaurant est fermé. Revenez demain pendant les heures d’ouverture.',
    it: 'Il ristorante ora è chiuso. Torna domani durante l’orario di apertura.',
    hu: 'Az étterem most zárva van. Gyere holnap nyitvatartási időben.',
    es: 'El restaurante está cerrado. Vuelve mañana en horario de apertura.',
  },
  // ── Rezervarea (ReservationSheet) ──
  rs_choose_date: {
    ro: 'Alege data',
    en: 'Choose a date',
    de: 'Wähle ein Datum',
    fr: 'Choisissez une date',
    it: 'Scegli la data',
    hu: 'Válassz dátumot',
    es: 'Elige la fecha',
  },
  rs_choose_time: {
    ro: 'Alege ora',
    en: 'Choose a time',
    de: 'Wähle eine Uhrzeit',
    fr: 'Choisissez une heure',
    it: 'Scegli l’orario',
    hu: 'Válassz időpontot',
    es: 'Elige la hora',
  },
  rs_name_required: {
    ro: 'Numele este obligatoriu',
    en: 'Name is required',
    de: 'Name ist erforderlich',
    fr: 'Le nom est obligatoire',
    it: 'Il nome è obbligatorio',
    hu: 'A név kötelező',
    es: 'El nombre es obligatorio',
  },
  rs_phone_required: {
    ro: 'Telefonul este obligatoriu',
    en: 'Phone is required',
    de: 'Telefonnummer ist erforderlich',
    fr: 'Le téléphone est obligatoire',
    it: 'Il telefono è obbligatorio',
    hu: 'A telefonszám kötelező',
    es: 'El teléfono es obligatorio',
  },
  rs_email_invalid: {
    ro: 'Email invalid',
    en: 'Invalid email',
    de: 'Ungültige E-Mail',
    fr: 'E-mail invalide',
    it: 'Email non valida',
    hu: 'Érvénytelen e-mail',
    es: 'Email no válido',
  },
  rs_unavailable_here: {
    ro: 'Rezervările nu sunt disponibile aici.',
    en: 'Reservations are unavailable here.',
    de: 'Reservierungen sind hier nicht verfügbar.',
    fr: 'Les réservations ne sont pas disponibles ici.',
    it: 'Le prenotazioni non sono disponibili qui.',
    hu: 'Itt nem lehet foglalni.',
    es: 'Las reservas no están disponibles aquí.',
  },
  rs_previous_cancelled: {
    ro: 'Rezervarea făcută anterior din această cerere a fost anulată. Trimite din nou pentru a face una nouă.',
    en: 'The reservation from this request was cancelled. Submit again to make a new one.',
    de: 'Die Reservierung aus dieser Anfrage wurde storniert. Sende erneut, um eine neue zu erstellen.',
    fr: 'La réservation issue de cette demande a été annulée. Renvoyez pour en faire une nouvelle.',
    it: 'La prenotazione di questa richiesta è stata annullata. Invia di nuovo per farne una nuova.',
    hu: 'Az ebből a kérésből készült foglalást törölték. Küldd el újra egy új foglaláshoz.',
    es: 'La reserva de esta solicitud se canceló. Envía de nuevo para hacer una nueva.',
  },
  rs_person_one: {
    ro: 'persoană',
    en: 'person',
    de: 'Person',
    fr: 'personne',
    it: 'persona',
    hu: 'fő',
    es: 'persona',
  },
  rs_person_many: {
    ro: 'persoane',
    en: 'people',
    de: 'Personen',
    fr: 'personnes',
    it: 'persone',
    hu: 'fő',
    es: 'personas',
  },
  rs_cannot_make_it: {
    ro: 'Nu mai poți ajunge?',
    en: 'Can’t make it?',
    de: 'Kannst du nicht kommen?',
    fr: 'Vous ne pouvez plus venir ?',
    it: 'Non riesci più a venire?',
    hu: 'Mégsem tudsz jönni?',
    es: '¿Ya no puedes venir?',
  },
  rs_cancel_online: {
    ro: 'Anulează online cu acest cod',
    en: 'Cancel online with this code',
    de: 'Online mit diesem Code stornieren',
    fr: 'Annuler en ligne avec ce code',
    it: 'Annulla online con questo codice',
    hu: 'Lemondás online ezzel a kóddal',
    es: 'Cancela en línea con este código',
  },
  rs_table_taken: {
    ro: 'Masa {name} e deja rezervată la ora aleasă.',
    en: 'Table {name} is already booked at the selected time.',
    de: 'Tisch {name} ist zur gewählten Zeit schon reserviert.',
    fr: 'La table {name} est déjà réservée à cette heure.',
    it: 'Il tavolo {name} è già prenotato all’orario scelto.',
    hu: 'A(z) {name}. asztal a választott időpontra már foglalt.',
    es: 'La mesa {name} ya está reservada a la hora elegida.',
  },
  rs_gdpr_note: {
    ro: 'Datele tale (nume, telefon, email) sunt folosite doar pentru gestionarea acestei rezervări.',
    en: 'Your details (name, phone, email) are used only to manage this reservation.',
    de: 'Deine Daten (Name, Telefon, E-Mail) werden nur zur Verwaltung dieser Reservierung verwendet.',
    fr: 'Vos données (nom, téléphone, e-mail) servent uniquement à gérer cette réservation.',
    it: 'I tuoi dati (nome, telefono, email) sono usati solo per gestire questa prenotazione.',
    hu: 'Adataidat (név, telefon, e-mail) csak ennek a foglalásnak a kezelésére használjuk.',
    es: 'Tus datos (nombre, teléfono, email) se usan solo para gestionar esta reserva.',
  },
  rs_privacy_policy: {
    ro: 'Politica de confidențialitate',
    en: 'Privacy policy',
    de: 'Datenschutzerklärung',
    fr: 'Politique de confidentialité',
    it: 'Informativa sulla privacy',
    hu: 'Adatvédelmi tájékoztató',
    es: 'Política de privacidad',
  },
  err_reservation_outside_hours: {
    ro: 'Ora aleasă este în afara programului. Alege altă oră.',
    en: 'The chosen time is outside opening hours. Pick another time.',
    de: 'Die gewählte Uhrzeit liegt außerhalb der Öffnungszeiten. Wähle eine andere.',
    fr: 'L’heure choisie est en dehors des heures d’ouverture. Choisissez-en une autre.',
    it: 'L’orario scelto è fuori dall’orario di apertura. Scegline un altro.',
    hu: 'A választott időpont nyitvatartási időn kívül esik. Válassz másikat.',
    es: 'La hora elegida está fuera del horario. Elige otra.',
  },
  err_party_too_large: {
    ro: 'Numărul de persoane depășește maximul permis online. Sună restaurantul.',
    en: 'The party size exceeds the online maximum. Please call the restaurant.',
    de: 'Die Personenzahl übersteigt das Online-Maximum. Bitte ruf das Restaurant an.',
    fr: 'Le nombre de personnes dépasse le maximum en ligne. Appelez le restaurant.',
    it: 'Il numero di persone supera il massimo online. Chiama il ristorante.',
    hu: 'A létszám meghaladja az online foglalható maximumot. Hívd fel az éttermet.',
    es: 'El número de personas supera el máximo en línea. Llama al restaurante.',
  },
  err_reservation_too_soon: {
    ro: 'Rezervarea e prea aproape de ora aleasă. Alege o oră mai târzie.',
    en: 'The reservation is too close to the chosen time. Pick a later time.',
    de: 'Die Reservierung ist zu kurzfristig. Wähle eine spätere Uhrzeit.',
    fr: 'La réservation est trop proche de l’heure choisie. Choisissez plus tard.',
    it: 'La prenotazione è troppo vicina all’orario scelto. Scegli un orario più tardi.',
    hu: 'A foglalás túl közel van a választott időponthoz. Válassz későbbit.',
    es: 'La reserva está demasiado cerca de la hora elegida. Elige una hora más tarde.',
  },
  err_reservation_too_far: {
    ro: 'Data aleasă e prea departe în viitor. Alege o dată mai apropiată.',
    en: 'The chosen date is too far ahead. Pick an earlier date.',
    de: 'Das gewählte Datum liegt zu weit in der Zukunft. Wähle ein früheres.',
    fr: 'La date choisie est trop lointaine. Choisissez une date plus proche.',
    it: 'La data scelta è troppo lontana. Scegli una data più vicina.',
    hu: 'A választott dátum túl messze van. Válassz korábbit.',
    es: 'La fecha elegida está demasiado lejos. Elige una más cercana.',
  },
  err_restaurant_not_found: {
    ro: 'Restaurantul nu a fost găsit.',
    en: 'Restaurant not found.',
    de: 'Restaurant nicht gefunden.',
    fr: 'Restaurant introuvable.',
    it: 'Ristorante non trovato.',
    hu: 'Az étterem nem található.',
    es: 'Restaurante no encontrado.',
  },
  // ── Meniul public /m/:slug (PublicMenuPage) ──
  rest_not_found_title: {
    ro: 'Restaurant negăsit',
    en: 'Restaurant not found',
    de: 'Restaurant nicht gefunden',
    fr: 'Restaurant introuvable',
    it: 'Ristorante non trovato',
    hu: 'Az étterem nem található',
    es: 'Restaurante no encontrado',
  },
  rest_not_found_msg: {
    ro: 'Verifică linkul sau încearcă din nou.',
    en: 'Check the link or try again.',
    de: 'Prüfe den Link oder versuche es erneut.',
    fr: 'Vérifiez le lien ou réessayez.',
    it: 'Controlla il link o riprova.',
    hu: 'Ellenőrizd a linket, vagy próbáld újra.',
    es: 'Revisa el enlace o inténtalo de nuevo.',
  },
  err_menu_conn: {
    ro: 'Conexiune eșuată. Verifică internetul și încearcă din nou.',
    en: 'Connection failed. Check your internet and try again.',
    de: 'Verbindung fehlgeschlagen. Prüfe dein Internet und versuche es erneut.',
    fr: 'Échec de la connexion. Vérifiez votre connexion et réessayez.',
    it: 'Connessione non riuscita. Controlla internet e riprova.',
    hu: 'A kapcsolódás nem sikerült. Ellenőrizd az internetet, és próbáld újra.',
    es: 'Error de conexión. Revisa internet e inténtalo de nuevo.',
  },
  website: {
    ro: 'Website',
    en: 'Website',
    de: 'Webseite',
    fr: 'Site web',
    it: 'Sito web',
    hu: 'Weboldal',
    es: 'Sitio web',
  },
} as const
