// ─────────────────────────────────────────────────────────────
// publicMenuStrings — i18n-ul chrome-ului de meniu client (7 limbi)
//
// OPT-11: extras din constants.ts — tabela (~20KB sursă) era trasă în
// chunk-ul de ENTRY prin importurile D/PLAN_LABELS din App/PageLoader, deși
// singurii consumatori sunt chunk-urile lazy QrMenuPage/PublicMenuPage/
// ReservationSheet. Modul fără niciun import propriu → intră doar în
// chunk-urile de meniu. Doctrina rămâne (CLAUDE.md): orice cheie NOUĂ are
// TOATE cele 7 câmpuri (altfel T() întoarce undefined la runtime); limbă
// nesuportată → fallback EN.
// ─────────────────────────────────────────────────────────────

// ── Mini i18n (doar pentru strings vizibile pe meniul public) ─
// Restaurantele cu language ∈ {ro, en, de, fr, it, hu, es} primesc textul lor;
// orice altă limbă primește fallback EN.
type PublicMenuLang = 'ro' | 'en' | 'de' | 'fr' | 'it' | 'hu' | 'es'

export const PUBLIC_MENU_STRINGS = {
  open_now: {
    ro: 'DESCHIS ACUM',
    en: 'OPEN NOW',
    de: 'JETZT GEÖFFNET',
    fr: 'OUVERT MAINTENANT',
    it: 'APERTO ORA',
    hu: 'MOST NYITVA',
    es: 'ABIERTO AHORA',
  },
  closed: {
    ro: 'ÎNCHIS',
    en: 'CLOSED',
    de: 'GESCHLOSSEN',
    fr: 'FERMÉ',
    it: 'CHIUSO',
    hu: 'ZÁRVA',
    es: 'CERRADO',
  },
  search_placeholder: {
    ro: 'Caută în meniu...',
    en: 'Search menu...',
    de: 'Menü durchsuchen...',
    fr: 'Rechercher au menu...',
    it: 'Cerca nel menu...',
    hu: 'Keresés a menüben...',
    es: 'Buscar en el menú...',
  },
  all_categories: {
    ro: 'Toate',
    en: 'All',
    de: 'Alle',
    fr: 'Tout',
    it: 'Tutti',
    hu: 'Összes',
    es: 'Todo',
  },
  no_results: {
    ro: 'Niciun rezultat',
    en: 'No results',
    de: 'Keine Ergebnisse',
    fr: 'Aucun résultat',
    it: 'Nessun risultato',
    hu: 'Nincs találat',
    es: 'Sin resultados',
  },
  clear_filters: {
    ro: 'Șterge filtrele',
    en: 'Clear filters',
    de: 'Filter löschen',
    fr: 'Effacer les filtres',
    it: 'Cancella filtri',
    hu: 'Szűrők törlése',
    es: 'Borrar filtros',
  },
  menu_by: {
    ro: 'MENIU BY MENUVIA',
    en: 'MENU BY MENUVIA',
    de: 'MENÜ BY MENUVIA',
    fr: 'MENU BY MENUVIA',
    it: 'MENU BY MENUVIA',
    hu: 'MENÜ BY MENUVIA',
    es: 'MENÚ BY MENUVIA',
  },
  today: {
    ro: 'Astăzi',
    en: 'Today',
    de: 'Heute',
    fr: "Aujourd'hui",
    it: 'Oggi',
    hu: 'Ma',
    es: 'Hoy',
  },
  back: {
    ro: 'Înapoi',
    en: 'Back',
    de: 'Zurück',
    fr: 'Retour',
    it: 'Indietro',
    hu: 'Vissza',
    es: 'Atrás',
  },
  pickup_badge: {
    ro: 'Comandă pentru ridicare',
    en: 'Order for pickup',
    de: 'Zum Abholen bestellen',
    fr: 'Commander à emporter',
    it: 'Ordina per il ritiro',
    hu: 'Rendelés elvitelre',
    es: 'Pedir para recoger',
  },
  reserve_cta: {
    ro: 'Rezervă o masă',
    en: 'Reserve a table',
    de: 'Tisch reservieren',
    fr: 'Réserver une table',
    it: 'Prenota un tavolo',
    hu: 'Asztalfoglalás',
    es: 'Reservar una mesa',
  },
  reserve_trust: {
    ro: 'Garantăm că rezervarea ta este transmisă',
    en: 'We guarantee your reservation is received',
    de: 'Wir garantieren, dass deine Reservierung ankommt',
    fr: 'Nous garantissons la bonne réception de votre réservation',
    it: 'Garantiamo che la tua prenotazione venga ricevuta',
    hu: 'Garantáljuk, hogy foglalásod megérkezik',
    es: 'Garantizamos que tu reserva se recibe',
  },
  reserve_party_label: {
    ro: 'NUMĂRUL DE PERSOANE',
    en: 'NUMBER OF PEOPLE',
    de: 'ANZAHL DER PERSONEN',
    fr: 'NOMBRE DE PERSONNES',
    it: 'NUMERO DI PERSONE',
    hu: 'SZEMÉLYEK SZÁMA',
    es: 'NÚMERO DE PERSONAS',
  },
  reserve_date_label: {
    ro: 'DATA REZERVĂRII',
    en: 'RESERVATION DATE',
    de: 'RESERVIERUNGSDATUM',
    fr: 'DATE DE RÉSERVATION',
    it: 'DATA DELLA PRENOTAZIONE',
    hu: 'FOGLALÁS DÁTUMA',
    es: 'FECHA DE LA RESERVA',
  },
  reserve_today: {
    ro: 'Astăzi',
    en: 'Today',
    de: 'Heute',
    fr: "Aujourd'hui",
    it: 'Oggi',
    hu: 'Ma',
    es: 'Hoy',
  },
  reserve_tomorrow: {
    ro: 'Mâine',
    en: 'Tomorrow',
    de: 'Morgen',
    fr: 'Demain',
    it: 'Domani',
    hu: 'Holnap',
    es: 'Mañana',
  },
  reserve_other_date: {
    ro: 'Altă dată',
    en: 'Other date',
    de: 'Anderes Datum',
    fr: 'Autre date',
    it: 'Altra data',
    hu: 'Másik dátum',
    es: 'Otra fecha',
  },
  reserve_zone_label: {
    ro: 'ZONA',
    en: 'AREA',
    de: 'BEREICH',
    fr: 'ZONE',
    it: 'ZONA',
    hu: 'TERÜLET',
    es: 'ZONA',
  },
  reserve_zone_any: {
    ro: 'Oriunde',
    en: 'Any area',
    de: 'Überall',
    fr: "N'importe où",
    it: 'Ovunque',
    hu: 'Bárhol',
    es: 'Cualquier zona',
  },
  reserve_time_label: {
    ro: 'ORA REZERVĂRII',
    en: 'RESERVATION HOUR',
    de: 'RESERVIERUNGSZEIT',
    fr: 'HEURE DE RÉSERVATION',
    it: 'ORA DELLA PRENOTAZIONE',
    hu: 'FOGLALÁS IDŐPONTJA',
    es: 'HORA DE LA RESERVA',
  },
  reserve_contact_label: {
    ro: 'CONTACT',
    en: 'CONTACT',
    de: 'KONTAKT',
    fr: 'CONTACT',
    it: 'CONTATTO',
    hu: 'KAPCSOLAT',
    es: 'CONTACTO',
  },
  reserve_name: {
    ro: 'Nume',
    en: 'Name',
    de: 'Name',
    fr: 'Nom',
    it: 'Nome',
    hu: 'Név',
    es: 'Nombre',
  },
  reserve_phone: {
    ro: 'Telefon',
    en: 'Phone',
    de: 'Telefon',
    fr: 'Téléphone',
    it: 'Telefono',
    hu: 'Telefon',
    es: 'Teléfono',
  },
  reserve_email_opt: {
    ro: 'Email (opțional)',
    en: 'Email (optional)',
    de: 'E-Mail (optional)',
    fr: 'E-mail (facultatif)',
    it: 'Email (facoltativo)',
    hu: 'E-mail (opcionális)',
    es: 'Correo (opcional)',
  },
  reserve_notes_opt: {
    ro: 'Observații (opțional)',
    en: 'Notes (optional)',
    de: 'Anmerkungen (optional)',
    fr: 'Remarques (facultatif)',
    it: 'Note (facoltativo)',
    hu: 'Megjegyzés (opcionális)',
    es: 'Notas (opcional)',
  },
  reserve_submit: {
    ro: 'Rezervă',
    en: 'Reserve',
    de: 'Reservieren',
    fr: 'Réserver',
    it: 'Prenota',
    hu: 'Foglalás',
    es: 'Reservar',
  },
  reserve_submitting: {
    ro: 'Se trimite...',
    en: 'Sending...',
    de: 'Wird gesendet...',
    fr: 'Envoi...',
    it: 'Invio in corso...',
    hu: 'Küldés...',
    es: 'Enviando...',
  },
  reserve_success_title: {
    ro: 'Rezervare confirmată!',
    en: 'Reservation confirmed!',
    de: 'Reservierung bestätigt!',
    fr: 'Réservation confirmée !',
    it: 'Prenotazione confermata!',
    hu: 'Foglalás megerősítve!',
    es: '¡Reserva confirmada!',
  },
  reserve_pending_title: {
    ro: 'Rezervare primită',
    en: 'Reservation received',
    de: 'Reservierung erhalten',
    fr: 'Réservation reçue',
    it: 'Prenotazione ricevuta',
    hu: 'Foglalás beérkezett',
    es: 'Reserva recibida',
  },
  reserve_pending_sub: {
    ro: 'Echipa restaurantului va confirma în scurt timp.',
    en: 'The venue will confirm shortly.',
    de: 'Das Restaurant bestätigt in Kürze.',
    fr: "L'établissement confirmera sous peu.",
    it: 'Il locale confermerà a breve.',
    hu: 'Az étterem hamarosan megerősíti.',
    es: 'El local confirmará en breve.',
  },
  reserve_pending_no_table_sub: {
    ro: 'Locul tău e rezervat — ospătarul îți alocă masa la sosire.',
    en: 'Your spot is held — the waiter will assign a table on arrival.',
    de: 'Dein Platz ist reserviert — der Kellner weist dir bei Ankunft einen Tisch zu.',
    fr: "Votre place est retenue — le serveur vous attribuera une table à l'arrivée.",
    it: "Il tuo posto è riservato — il cameriere ti assegnerà un tavolo all'arrivo.",
    hu: 'A helyed foglalva van — a pincér érkezéskor asztalt jelöl ki.',
    es: 'Tu lugar está reservado — el camarero te asignará una mesa al llegar.',
  },
  reserve_code_label: {
    ro: 'COD REZERVARE',
    en: 'BOOKING CODE',
    de: 'BUCHUNGSCODE',
    fr: 'CODE DE RÉSERVATION',
    it: 'CODICE PRENOTAZIONE',
    hu: 'FOGLALÁSI KÓD',
    es: 'CÓDIGO DE RESERVA',
  },
  reserve_back_to_menu: {
    ro: 'Înapoi la meniu',
    en: 'Back to menu',
    de: 'Zurück zum Menü',
    fr: 'Retour au menu',
    it: 'Torna al menu',
    hu: 'Vissza a menühöz',
    es: 'Volver al menú',
  },
  reserve_post_paid_cta: {
    ro: 'Rezervă o masă',
    en: 'Reserve a table',
    de: 'Tisch reservieren',
    fr: 'Réserver une table',
    it: 'Prenota un tavolo',
    hu: 'Asztalfoglalás',
    es: 'Reservar una mesa',
  },
  reserve_post_paid_sub: {
    ro: 'Pentru data viitoare',
    en: 'For your next visit',
    de: 'Für deinen nächsten Besuch',
    fr: 'Pour votre prochaine visite',
    it: 'Per la tua prossima visita',
    hu: 'A következő látogatásodra',
    es: 'Para tu próxima visita',
  },
  reserve_no_slots: {
    ro: 'Nu există slot-uri disponibile',
    en: 'No available slots',
    de: 'Keine freien Zeitfenster',
    fr: 'Aucun créneau disponible',
    it: 'Nessuno slot disponibile',
    hu: 'Nincs szabad időpont',
    es: 'No hay horarios disponibles',
  },
  reserve_call_if_change: {
    ro: 'Sună dacă nu mai poți veni',
    en: 'Call if you can no longer make it',
    de: 'Ruf an, falls du nicht kommen kannst',
    fr: 'Appelez si vous ne pouvez plus venir',
    it: 'Chiama se non puoi più venire',
    hu: 'Hívj, ha mégsem tudsz jönni',
    es: 'Llama si ya no puedes venir',
  },
  reserve_email_reminder: {
    ro: 'Vei primi un email reminder înainte de vizită.',
    en: 'You will receive an email reminder before your visit.',
    de: 'Du erhältst vor deinem Besuch eine Erinnerungs-E-Mail.',
    fr: 'Vous recevrez un e-mail de rappel avant votre visite.',
    it: 'Riceverai un promemoria via email prima della visita.',
    hu: 'A látogatásod előtt emlékeztető e-mailt kapsz.',
    es: 'Recibirás un correo recordatorio antes de tu visita.',
  },
  // Alegerea mesei pe harta sălii (secțiune opțională, apare doar cu floor plan).
  reserve_add_another: {
    ro: '+ Rezervă altă masă',
    en: '+ Book another table',
    de: '+ Weiteren Tisch reservieren',
    fr: '+ Réserver une autre table',
    it: '+ Prenota un altro tavolo',
    hu: '+ Másik asztal foglalása',
    es: '+ Reservar otra mesa',
  },
  reserve_pick_table_label: {
    ro: 'ALEGE MASA (OPȚIONAL)',
    en: 'CHOOSE A TABLE (OPTIONAL)',
    de: 'TISCH WÄHLEN (OPTIONAL)',
    fr: 'CHOISIR UNE TABLE (FACULTATIF)',
    it: 'SCEGLI UN TAVOLO (FACOLTATIVO)',
    hu: 'VÁLASSZ ASZTALT (OPCIONÁLIS)',
    es: 'ELIGE UNA MESA (OPCIONAL)',
  },
  reserve_any_free_table: {
    ro: 'Oricare masă liberă',
    en: 'Any free table',
    de: 'Beliebiger freier Tisch',
    fr: "N'importe quelle table libre",
    it: 'Qualsiasi tavolo libero',
    hu: 'Bármelyik szabad asztal',
    es: 'Cualquier mesa libre',
  },
  reserve_pick_table_hint: {
    ro: 'Atinge o masă liberă pentru a o alege, sau lasă „Oricare masă liberă" pentru alocare automată.',
    en: 'Tap a free table to pick it, or keep “Any free table” for automatic assignment.',
    de: 'Tippe auf einen freien Tisch, um ihn zu wählen, oder behalte „Beliebiger freier Tisch“ für die automatische Zuweisung.',
    fr: 'Touchez une table libre pour la choisir, ou gardez « N’importe quelle table libre » pour une attribution automatique.',
    it: 'Tocca un tavolo libero per sceglierlo, oppure lascia «Qualsiasi tavolo libero» per l’assegnazione automatica.',
    hu: 'Érints meg egy szabad asztalt a kiválasztáshoz, vagy hagyd a „Bármelyik szabad asztal“ opciót az automatikus kijelöléshez.',
    es: 'Toca una mesa libre para elegirla, o deja «Cualquier mesa libre» para la asignación automática.',
  },
  reserve_map_loading: {
    ro: 'Se încarcă harta sălii…',
    en: 'Loading floor plan…',
    de: 'Saalplan wird geladen…',
    fr: 'Chargement du plan de salle…',
    it: 'Caricamento della piantina…',
    hu: 'Teremtérkép betöltése…',
    es: 'Cargando el plano de la sala…',
  },
  reserve_map_error: {
    ro: 'Harta sălii nu s-a putut încărca — poți continua cu alocare automată.',
    en: 'The floor plan could not be loaded — you can continue with automatic assignment.',
    de: 'Der Saalplan konnte nicht geladen werden — du kannst mit automatischer Zuweisung fortfahren.',
    fr: 'Le plan de salle n’a pas pu être chargé — vous pouvez continuer avec une attribution automatique.',
    it: 'Impossibile caricare la piantina — puoi continuare con l’assegnazione automatica.',
    hu: 'A teremtérképet nem sikerült betölteni — folytathatod az automatikus kijelöléssel.',
    es: 'No se pudo cargar el plano de la sala — puedes continuar con la asignación automática.',
  },
  reserve_seats_word: {
    ro: 'locuri',
    en: 'seats',
    de: 'Plätze',
    fr: 'places',
    it: 'posti',
    hu: 'férőhely',
    es: 'plazas',
  },
  reserve_deselect_table: {
    ro: 'Deselectează masa',
    en: 'Deselect table',
    de: 'Tischauswahl aufheben',
    fr: 'Désélectionner la table',
    it: 'Deseleziona il tavolo',
    hu: 'Asztal kijelölésének visszavonása',
    es: 'Anular selección de mesa',
  },
  // Banner Happy Hour (prefixul; sufixele -%/-lei rămân în afara dicționarului).
  happy_hour_active: {
    ro: 'Happy Hour activ:',
    en: 'Happy Hour active:',
    de: 'Happy Hour aktiv:',
    fr: 'Happy Hour actif :',
    it: 'Happy Hour attivo:',
    hu: 'Happy Hour aktív:',
    es: 'Happy Hour activo:',
  },
  // Bara sticky + sheet-ul „Lista mea" (meniu digital fără comenzi).
  my_list: {
    ro: 'Lista mea',
    en: 'My list',
    de: 'Meine Liste',
    fr: 'Ma liste',
    it: 'La mia lista',
    hu: 'Listám',
    es: 'Mi lista',
  },
  view_cart: {
    ro: 'Vezi coșul',
    en: 'View cart',
    de: 'Warenkorb ansehen',
    fr: 'Voir le panier',
    it: 'Vedi il carrello',
    hu: 'Kosár megtekintése',
    es: 'Ver el carrito',
  },
  // Plural produs/produse (en: item/items — pluralul e ales de apelant pe count).
  item_one: {
    ro: 'produs',
    en: 'item',
    de: 'Artikel',
    fr: 'article',
    it: 'articolo',
    hu: 'termék',
    es: 'artículo',
  },
  item_many: {
    ro: 'produse',
    en: 'items',
    de: 'Artikel',
    fr: 'articles',
    it: 'articoli',
    hu: 'termék',
    es: 'artículos',
  },
  in_my_list: {
    ro: 'în lista mea',
    en: 'in my list',
    de: 'in meiner Liste',
    fr: 'dans ma liste',
    it: 'nella mia lista',
    hu: 'a listámon',
    es: 'en mi lista',
  },
  in_cart: {
    ro: 'în coș',
    en: 'in cart',
    de: 'im Warenkorb',
    fr: 'dans le panier',
    it: 'nel carrello',
    hu: 'a kosárban',
    es: 'en el carrito',
  },
  list_hint: {
    ro: 'Lista mea · atinge un produs ca să adaugi',
    en: 'My list · tap a product to add',
    de: 'Meine Liste · tippe auf ein Produkt zum Hinzufügen',
    fr: 'Ma liste · touchez un produit pour l’ajouter',
    it: 'La mia lista · tocca un prodotto per aggiungerlo',
    hu: 'Listám · érints meg egy terméket a hozzáadáshoz',
    es: 'Mi lista · toca un producto para añadirlo',
  },
  order_yours: {
    ro: 'Comanda ta',
    en: 'Your order',
    de: 'Deine Bestellung',
    fr: 'Votre commande',
    it: 'Il tuo ordine',
    hu: 'A rendelésed',
    es: 'Tu pedido',
  },
  list_subtitle: {
    ro: 'Ce vrei să iei — salvat pe telefonul tău. Arată-i ospătarului când comanzi.',
    en: 'What you want to get — saved on your phone. Show it to the waiter when you order.',
    de: 'Was du möchtest — auf deinem Handy gespeichert. Zeig es dem Kellner beim Bestellen.',
    fr: 'Ce que vous voulez prendre — enregistré sur votre téléphone. Montrez-le au serveur au moment de commander.',
    it: 'Cosa vuoi prendere — salvato sul tuo telefono. Mostralo al cameriere quando ordini.',
    hu: 'Amit szeretnél — a telefonodra mentve. Mutasd meg a pincérnek, amikor rendelsz.',
    es: 'Lo que quieres pedir — guardado en tu teléfono. Muéstraselo al camarero al ordenar.',
  },
  list_empty: {
    ro: 'Lista e goală. Atinge un produs din meniu ca să-l adaugi aici.',
    en: 'Your list is empty. Tap a product in the menu to add it here.',
    de: 'Deine Liste ist leer. Tippe im Menü auf ein Produkt, um es hier hinzuzufügen.',
    fr: 'Votre liste est vide. Touchez un produit du menu pour l’ajouter ici.',
    it: 'La tua lista è vuota. Tocca un prodotto nel menu per aggiungerlo qui.',
    hu: 'A listád üres. Érints meg egy terméket a menüből, hogy ide add.',
    es: 'Tu lista está vacía. Toca un producto del menú para añadirlo aquí.',
  },
  remove: {
    ro: 'Elimină',
    en: 'Remove',
    de: 'Entfernen',
    fr: 'Retirer',
    it: 'Rimuovi',
    hu: 'Eltávolítás',
    es: 'Quitar',
  },
  total: {
    ro: 'Total',
    en: 'Total',
    de: 'Gesamt',
    fr: 'Total',
    it: 'Totale',
    hu: 'Összesen',
    es: 'Total',
  },
  clear_list: {
    ro: 'Golește lista',
    en: 'Clear list',
    de: 'Liste leeren',
    fr: 'Vider la liste',
    it: 'Svuota la lista',
    hu: 'Lista ürítése',
    es: 'Vaciar la lista',
  },
  close: {
    ro: 'Închide',
    en: 'Close',
    de: 'Schließen',
    fr: 'Fermer',
    it: 'Chiudi',
    hu: 'Bezárás',
    es: 'Cerrar',
  },
  // ── Loyalty v1 (mig 226): cardul de puncte pe QR ──────────────
  loyalty_points: {
    ro: 'Puncte de fidelitate',
    en: 'Loyalty points',
    de: 'Treuepunkte',
    fr: 'Points de fidélité',
    it: 'Punti fedeltà',
    hu: 'Hűségpontok',
    es: 'Puntos de fidelidad',
  },
  loyalty_progress_aria: {
    ro: 'Progres puncte de fidelitate',
    en: 'Loyalty points progress',
    de: 'Fortschritt der Treuepunkte',
    fr: 'Progression des points de fidélité',
    it: 'Avanzamento punti fedeltà',
    hu: 'Hűségpontok haladása',
    es: 'Progreso de puntos de fidelidad',
  },
  // Fragmentele frazei de recompensă (bold-urile desc/cod se inserează în JSX).
  loyalty_reward_have: {
    ro: 'Ai o recompensă:',
    en: 'You have a reward:',
    de: 'Du hast eine Belohnung:',
    fr: 'Vous avez une récompense :',
    it: 'Hai un premio:',
    hu: 'Van egy jutalmad:',
    es: 'Tienes una recompensa:',
  },
  loyalty_show_code: {
    ro: 'Arată codul',
    en: 'Show the code',
    de: 'Zeig den Code',
    fr: 'Montrez le code',
    it: 'Mostra il codice',
    hu: 'Mutasd a kódot',
    es: 'Muestra el código',
  },
  loyalty_to_waiter: {
    ro: 'ospătarului.',
    en: 'to the waiter.',
    de: 'dem Kellner.',
    fr: 'au serveur.',
    it: 'al cameriere.',
    hu: 'a pincérnek.',
    es: 'al camarero.',
  },
  // Fragmentele hint-ului „câștigi puncte" (numărul de prag se inserează în JSX).
  loyalty_earn_hint_pre: {
    ro: 'Primești puncte la fiecare comandă. La',
    en: 'You earn points with every order. At',
    de: 'Du sammelst bei jeder Bestellung Punkte. Bei',
    fr: 'Vous gagnez des points à chaque commande. À',
    it: 'Guadagni punti a ogni ordine. A',
    hu: 'Minden rendelésnél pontokat gyűjtesz.',
    es: 'Ganas puntos en cada pedido. A los',
  },
  loyalty_points_word: {
    ro: 'puncte:',
    en: 'points:',
    de: 'Punkten:',
    fr: 'points :',
    it: 'punti:',
    hu: 'pontnál:',
    es: 'puntos:',
  },
  loyalty_phone_opt: {
    ro: 'Telefon (opțional)',
    en: 'Phone (optional)',
    de: 'Telefon (optional)',
    fr: 'Téléphone (facultatif)',
    it: 'Telefono (facoltativo)',
    hu: 'Telefon (opcionális)',
    es: 'Teléfono (opcional)',
  },
  loyalty_phone_aria: {
    ro: 'Telefon pentru puncte de fidelitate',
    en: 'Phone for loyalty points',
    de: 'Telefon für Treuepunkte',
    fr: 'Téléphone pour les points de fidélité',
    it: 'Telefono per i punti fedeltà',
    hu: 'Telefonszám a hűségpontokhoz',
    es: 'Teléfono para los puntos de fidelidad',
  },
  saved: {
    ro: 'Salvat ✓',
    en: 'Saved ✓',
    de: 'Gespeichert ✓',
    fr: 'Enregistré ✓',
    it: 'Salvato ✓',
    hu: 'Mentve ✓',
    es: 'Guardado ✓',
  },
  save: {
    ro: 'Salvează',
    en: 'Save',
    de: 'Speichern',
    fr: 'Enregistrer',
    it: 'Salva',
    hu: 'Mentés',
    es: 'Guardar',
  },
  loyalty_phone_hint: {
    ro: 'Cu telefonul nu-ți pierzi punctele dacă schimbi dispozitivul. Îl folosim doar pentru puncte și îl stocăm criptat (hash), nu ca număr.',
    en: "With your phone number you won't lose your points if you switch devices. We use it only for points and store it encrypted (hashed), not as a number.",
    de: 'Mit deiner Telefonnummer verlierst du deine Punkte nicht, wenn du das Gerät wechselst. Wir nutzen sie nur für Punkte und speichern sie verschlüsselt (Hash), nicht als Nummer.',
    fr: "Avec votre numéro, vous ne perdez pas vos points si vous changez d'appareil. Nous l'utilisons uniquement pour les points et le stockons chiffré (haché), pas en clair.",
    it: 'Con il tuo numero non perdi i punti se cambi dispositivo. Lo usiamo solo per i punti e lo memorizziamo cifrato (hash), non come numero.',
    hu: 'A telefonszámoddal nem veszíted el a pontjaidat, ha eszközt váltasz. Csak a pontokhoz használjuk, és titkosítva (hash) tároljuk, nem számként.',
    es: 'Con tu número no pierdes los puntos si cambias de dispositivo. Lo usamos solo para los puntos y lo guardamos cifrado (hash), no como número.',
  },
  // ── Butoanele de sesiune QR: cheamă ospătarul / cere nota ─────
  call_waiter: {
    ro: 'Cheamă ospătarul',
    en: 'Call the waiter',
    de: 'Kellner rufen',
    fr: 'Appeler le serveur',
    it: 'Chiama il cameriere',
    hu: 'Pincér hívása',
    es: 'Llamar al camarero',
  },
  waiter_calling: {
    ro: 'Se cheamă...',
    en: 'Calling...',
    de: 'Wird gerufen...',
    fr: 'Appel...',
    it: 'Chiamata in corso...',
    hu: 'Hívás...',
    es: 'Llamando...',
  },
  waiter_called: {
    ro: 'Am anunțat ospătarul',
    en: 'The waiter has been notified',
    de: 'Der Kellner wurde benachrichtigt',
    fr: 'Le serveur a été prévenu',
    it: 'Il cameriere è stato avvisato',
    hu: 'A pincért értesítettük',
    es: 'Se avisó al camarero',
  },
  request_bill: {
    ro: 'Cere nota',
    en: 'Ask for the bill',
    de: 'Rechnung anfordern',
    fr: "Demander l'addition",
    it: 'Chiedi il conto',
    hu: 'Számla kérése',
    es: 'Pedir la cuenta',
  },
  bill_on_way: {
    ro: 'Nota e pe drum',
    en: 'The bill is on its way',
    de: 'Die Rechnung kommt',
    fr: "L'addition arrive",
    it: 'Il conto sta arrivando',
    hu: 'A számla úton van',
    es: 'La cuenta está en camino',
  },
  sending: {
    ro: 'Se trimite...',
    en: 'Sending...',
    de: 'Wird gesendet...',
    fr: 'Envoi...',
    it: 'Invio in corso...',
    hu: 'Küldés...',
    es: 'Enviando...',
  },
  // ── Sheet-ul de bacșiș la „Cere nota" (E1, mig 223) ───────────
  tip_sheet_aria: {
    ro: 'Cere nota cu bacșiș',
    en: 'Ask for the bill with a tip',
    de: 'Rechnung mit Trinkgeld anfordern',
    fr: "Demander l'addition avec pourboire",
    it: 'Chiedi il conto con mancia',
    hu: 'Számla kérése borravalóval',
    es: 'Pedir la cuenta con propina',
  },
  tip_title: {
    ro: 'Ceri nota',
    en: 'Ask for the bill',
    de: 'Rechnung anfordern',
    fr: "Demander l'addition",
    it: 'Chiedi il conto',
    hu: 'Számla kérése',
    es: 'Pedir la cuenta',
  },
  tip_subtitle: {
    ro: 'Vrei să lași bacșiș? Suma ajunge la ospătar odată cu nota — plătești ca de obicei.',
    en: 'Want to leave a tip? The amount reaches the waiter along with the bill — you pay as usual.',
    de: 'Möchtest du Trinkgeld geben? Der Betrag geht mit der Rechnung an den Kellner — du zahlst wie gewohnt.',
    fr: "Envie de laisser un pourboire ? Le montant parvient au serveur avec l'addition — vous payez comme d'habitude.",
    it: "Vuoi lasciare una mancia? L'importo arriva al cameriere insieme al conto — paghi come al solito.",
    hu: 'Adnál borravalót? Az összeg a számlával együtt jut el a pincérhez — a szokásos módon fizetsz.',
    es: '¿Quieres dejar propina? El importe llega al camarero junto con la cuenta — pagas como siempre.',
  },
  tip_none: {
    ro: 'Fără',
    en: 'None',
    de: 'Kein',
    fr: 'Aucun',
    it: 'Nessuna',
    hu: 'Nincs',
    es: 'Ninguna',
  },
  tip_other_amount: {
    ro: 'Altă sumă',
    en: 'Other amount',
    de: 'Anderer Betrag',
    fr: 'Autre montant',
    it: 'Altro importo',
    hu: 'Más összeg',
    es: 'Otro importe',
  },
  tip_other_aria: {
    ro: 'Bacșiș — altă sumă',
    en: 'Tip — other amount',
    de: 'Trinkgeld — anderer Betrag',
    fr: 'Pourboire — autre montant',
    it: 'Mancia — altro importo',
    hu: 'Borravaló — más összeg',
    es: 'Propina — otro importe',
  },
  send: {
    ro: 'Trimite',
    en: 'Send',
    de: 'Senden',
    fr: 'Envoyer',
    it: 'Invia',
    hu: 'Küldés',
    es: 'Enviar',
  },
  // ── Bara „Comanda mea" (empty state pe QR) ────────────────────
  my_order: {
    ro: 'Comanda mea',
    en: 'My order',
    de: 'Meine Bestellung',
    fr: 'Ma commande',
    it: 'Il mio ordine',
    hu: 'A rendelésem',
    es: 'Mi pedido',
  },
  my_order_hint: {
    ro: 'Comanda mea · atinge un produs ca să începi',
    en: 'My order · tap a product to start',
    de: 'Meine Bestellung · tippe auf ein Produkt zum Starten',
    fr: 'Ma commande · touchez un produit pour commencer',
    it: 'Il mio ordine · tocca un prodotto per iniziare',
    hu: 'A rendelésem · érints meg egy terméket a kezdéshez',
    es: 'Mi pedido · toca un producto para empezar',
  },
  // ── Pickup checkout + confirmare (PublicMenuPage /m/:slug) ────
  cart_empty: {
    ro: 'Coșul e gol — adaugă produse din meniu.',
    en: 'Your cart is empty — add products from the menu.',
    de: 'Dein Warenkorb ist leer — füge Produkte aus dem Menü hinzu.',
    fr: 'Votre panier est vide — ajoutez des produits du menu.',
    it: 'Il carrello è vuoto — aggiungi prodotti dal menu.',
    hu: 'A kosarad üres — adj hozzá termékeket a menüből.',
    es: 'Tu carrito está vacío — añade productos del menú.',
  },
  continue_to_pickup: {
    ro: 'Continuă la ridicare',
    en: 'Continue to pickup',
    de: 'Weiter zur Abholung',
    fr: 'Continuer vers le retrait',
    it: 'Continua al ritiro',
    hu: 'Tovább az átvételhez',
    es: 'Continuar a la recogida',
  },
  order_placed: {
    ro: 'Comandă plasată!',
    en: 'Order placed!',
    de: 'Bestellung aufgegeben!',
    fr: 'Commande passée !',
    it: 'Ordine effettuato!',
    hu: 'Rendelés leadva!',
    es: '¡Pedido realizado!',
  },
  // Fragmentele frazei de confirmare (numărul comenzii bold se inserează în JSX).
  order_sent_pre: {
    ro: 'Comanda',
    en: 'Order',
    de: 'Bestellung',
    fr: 'La commande',
    it: "L'ordine",
    hu: 'A rendelés',
    es: 'El pedido',
  },
  order_sent_post: {
    ro: 'a fost trimisă restaurantului.',
    en: 'has been sent to the restaurant.',
    de: 'wurde an das Restaurant gesendet.',
    fr: 'a été envoyée au restaurant.',
    it: 'è stato inviato al ristorante.',
    hu: 'elküldve az étterembe.',
    es: 'se ha enviado al restaurante.',
  },
  pickup_come_at_pre: {
    ro: 'Vino la',
    en: 'Come at',
    de: 'Komm um',
    fr: 'Venez à',
    it: 'Vieni alle',
    hu: 'Gyere',
    es: 'Ven a las',
  },
  pickup_come_at_post: {
    ro: 'să o ridici.',
    en: 'to pick it up.',
    de: 'Uhr, um sie abzuholen.',
    fr: 'pour la récupérer.',
    it: 'per ritirarlo.',
    hu: 'órakor átvenni.',
    es: 'para recogerlo.',
  },
  total_due_pickup: {
    ro: 'Total de plată la ridicare:',
    en: 'Total due at pickup:',
    de: 'Zu zahlen bei Abholung:',
    fr: 'Total à payer au retrait :',
    it: 'Totale da pagare al ritiro:',
    hu: 'Fizetendő átvételkor:',
    es: 'Total a pagar en la recogida:',
  },
  thanks: {
    ro: 'Mulțumim!',
    en: 'Thank you!',
    de: 'Danke!',
    fr: 'Merci !',
    it: 'Grazie!',
    hu: 'Köszönjük!',
    es: '¡Gracias!',
  },
} as const

export type PublicMenuStringKey = keyof typeof PUBLIC_MENU_STRINGS

const SUPPORTED_PUBLIC_MENU_LANGS: readonly PublicMenuLang[] = [
  'ro',
  'en',
  'de',
  'fr',
  'it',
  'hu',
  'es',
]

export function T(lang: string | null | undefined, key: PublicMenuStringKey): string {
  const normalized: PublicMenuLang = (SUPPORTED_PUBLIC_MENU_LANGS as readonly string[]).includes(
    lang ?? '',
  )
    ? (lang as PublicMenuLang)
    : 'en'
  return PUBLIC_MENU_STRINGS[key][normalized]
}
